/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence.entity.Estadisticasdia_InscripcionEntity;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence.converter.Dia_InscripcionConverter;
import co.edu.uniandes.csw.G3xtreme.empresa.logic.dto.EmpresaDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence.entity.EstadisticasempresaEntity;
import co.edu.uniandes.csw.G3xtreme.empresa.persistence.converter.EmpresaConverter;
import co.edu.uniandes.csw.G3xtreme.estadisticas.logic.dto.EstadisticasDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.master.logic.dto.EstadisticasMasterDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence.api._IEstadisticasMasterPersistence;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.api.IEstadisticasPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _EstadisticasMasterPersistence implements _IEstadisticasMasterPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IEstadisticasPersistence estadisticasPersistence;  

    public EstadisticasMasterDTO getEstadisticas(Long estadisticasId) {
        EstadisticasMasterDTO estadisticasMasterDTO = new EstadisticasMasterDTO();
        EstadisticasDTO estadisticas = estadisticasPersistence.getEstadisticas(estadisticasId);
        estadisticasMasterDTO.setEstadisticasEntity(estadisticas);
        estadisticasMasterDTO.setListdia_Inscripcion(getEstadisticasdia_InscripcionEntityList(estadisticasId));
        estadisticasMasterDTO.setListempresa(getEstadisticasempresaEntityList(estadisticasId));
        return estadisticasMasterDTO;
    }

    public Estadisticasdia_InscripcionEntity createEstadisticasdia_InscripcionEntity(Estadisticasdia_InscripcionEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteEstadisticasdia_InscripcionEntity(Long estadisticasId, Long dia_InscripcionId) {
        Query q = entityManager.createNamedQuery("Estadisticasdia_InscripcionEntity.deleteEstadisticasdia_InscripcionEntity");
        q.setParameter("estadisticasId", estadisticasId);
        q.setParameter("dia_InscripcionId", dia_InscripcionId);
        q.executeUpdate();
    }

    public List<Dia_InscripcionDTO> getEstadisticasdia_InscripcionEntityList(Long estadisticasId) {
        ArrayList<Dia_InscripcionDTO> resp = new ArrayList<Dia_InscripcionDTO>();
        Query q = entityManager.createNamedQuery("Estadisticasdia_InscripcionEntity.getByMasterId");
        q.setParameter("estadisticasId",estadisticasId);
        List<Estadisticasdia_InscripcionEntity> qResult =  q.getResultList();
        for (Estadisticasdia_InscripcionEntity entity : qResult) { 
            if(entity.getDia_InscripcionIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(Dia_InscripcionConverter.entity2PersistenceDTO(entity.getDia_InscripcionIdEntity()));
        }
        return resp;
    }
    public EstadisticasempresaEntity createEstadisticasempresaEntity(EstadisticasempresaEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteEstadisticasempresaEntity(Long estadisticasId, Long empresaId) {
        Query q = entityManager.createNamedQuery("EstadisticasempresaEntity.deleteEstadisticasempresaEntity");
        q.setParameter("estadisticasId", estadisticasId);
        q.setParameter("empresaId", empresaId);
        q.executeUpdate();
    }

    public List<EmpresaDTO> getEstadisticasempresaEntityList(Long estadisticasId) {
        ArrayList<EmpresaDTO> resp = new ArrayList<EmpresaDTO>();
        Query q = entityManager.createNamedQuery("EstadisticasempresaEntity.getByMasterId");
        q.setParameter("estadisticasId",estadisticasId);
        List<EstadisticasempresaEntity> qResult =  q.getResultList();
        for (EstadisticasempresaEntity entity : qResult) { 
            if(entity.getEmpresaIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EmpresaConverter.entity2PersistenceDTO(entity.getEmpresaIdEntity()));
        }
        return resp;
    }

}
