/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.expositor.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G3xtreme.expositor.logic.dto.ExpositorDTO;
import co.edu.uniandes.csw.G3xtreme.expositor.logic.dto.ExpositorPageDTO;
import co.edu.uniandes.csw.G3xtreme.expositor.persistence.api._IExpositorPersistence;
import co.edu.uniandes.csw.G3xtreme.expositor.persistence.converter.ExpositorConverter;
import co.edu.uniandes.csw.G3xtreme.expositor.persistence.entity.ExpositorEntity;

public abstract class _ExpositorPersistence implements _IExpositorPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
	protected EntityManager entityManager;
	
	public ExpositorDTO createExpositor(ExpositorDTO expositor) {
		ExpositorEntity entity=ExpositorConverter.persistenceDTO2Entity(expositor);
		entityManager.persist(entity);
		return ExpositorConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ExpositorDTO> getExpositors() {
		Query q = entityManager.createQuery("select u from ExpositorEntity u");
		return ExpositorConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ExpositorPageDTO getExpositors(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ExpositorEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ExpositorEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ExpositorPageDTO response = new ExpositorPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ExpositorConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ExpositorDTO getExpositor(Long id) {
		return ExpositorConverter.entity2PersistenceDTO(entityManager.find(ExpositorEntity.class, id));
	}

	public void deleteExpositor(Long id) {
		ExpositorEntity entity=entityManager.find(ExpositorEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateExpositor(ExpositorDTO detail) {
		ExpositorEntity entity=entityManager.merge(ExpositorConverter.persistenceDTO2Entity(detail));
		ExpositorConverter.entity2PersistenceDTO(entity);
	}

}