/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.tarea.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaDTO;
import co.edu.uniandes.csw.G3xtreme.tarea.persistence.entity.TareaEntity;

public abstract class _TareaConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static TareaDTO entity2PersistenceDTO(TareaEntity entity){
		if (entity != null) {
			TareaDTO dto = new TareaDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setResponsable(entity.getResponsable());
 
			    if(entity.getFechaInicio() != null){
					dto.setFechaInicio(DATE_FORMAT.format(entity.getFechaInicio()));
				}	
 
			    if(entity.getFechaFin() != null){
					dto.setFechaFin(DATE_FORMAT.format(entity.getFechaFin()));
				}	
					dto.setDescripcion(entity.getDescripcion());
					dto.setEstado(entity.getEstado());
					dto.setResponsable_tareaId(entity.getResponsable_tareaId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static TareaEntity persistenceDTO2Entity(TareaDTO dto){
		if(dto!=null){
			TareaEntity entity=new TareaEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setResponsable(dto.getResponsable());
			
 
			      try{ 
			        if(dto.getFechaInicio() != null){
						entity.setFechaInicio(DATE_FORMAT.parse(dto.getFechaInicio()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_TareaConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
 
			      try{ 
			        if(dto.getFechaFin() != null){
						entity.setFechaFin(DATE_FORMAT.parse(dto.getFechaFin()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_TareaConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setDescripcion(dto.getDescripcion());
			
					entity.setEstado(dto.getEstado());
			
					entity.setResponsable_tareaId(dto.getResponsable_tareaId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<TareaDTO> entity2PersistenceDTOList(List<TareaEntity> entities){
		List<TareaDTO> dtos=new ArrayList<TareaDTO>();
		for(TareaEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<TareaEntity> persistenceDTO2EntityList(List<TareaDTO> dtos){
		List<TareaEntity> entities=new ArrayList<TareaEntity>();
		for(TareaDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}