/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.estadisticas.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.estadisticas.logic.dto.EstadisticasPageDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.logic.dto.EstadisticasDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.api.IEstadisticasPersistence;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.entity.EstadisticasEntity;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.converter.EstadisticasConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EstadisticasPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EstadisticasPersistence.class.getPackage())
				.addPackage(EstadisticasEntity.class.getPackage())
				.addPackage(IEstadisticasPersistence.class.getPackage())
                .addPackage(EstadisticasDTO.class.getPackage())
                .addPackage(EstadisticasConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEstadisticasPersistence estadisticasPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EstadisticasEntity").executeUpdate();
	}

	private List<EstadisticasEntity> data=new ArrayList<EstadisticasEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EstadisticasEntity entity=new EstadisticasEntity();
			entity.setName(generateRandom(String.class));
			entity.setTotalInscritos(generateRandom(Integer.class));
			entity.setAsistenetesTiempoReal(generateRandom(Integer.class));
			entity.setVisitasAPlataformaInscripcion(generateRandom(Integer.class));
			entity.setMemoria(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEstadisticasTest(){
		EstadisticasDTO dto=new EstadisticasDTO();
		dto.setName(generateRandom(String.class));
		dto.setTotalInscritos(generateRandom(Integer.class));
		dto.setAsistenetesTiempoReal(generateRandom(Integer.class));
		dto.setVisitasAPlataformaInscripcion(generateRandom(Integer.class));
		dto.setMemoria(generateRandom(String.class));
		
		EstadisticasDTO result=estadisticasPersistence.createEstadisticas(dto);
		
		Assert.assertNotNull(result);
		
		EstadisticasEntity entity=em.find(EstadisticasEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getTotalInscritos(), entity.getTotalInscritos());
		Assert.assertEquals(dto.getAsistenetesTiempoReal(), entity.getAsistenetesTiempoReal());
		Assert.assertEquals(dto.getVisitasAPlataformaInscripcion(), entity.getVisitasAPlataformaInscripcion());
		Assert.assertEquals(dto.getMemoria(), entity.getMemoria());
	}
	
	@Test
	public void getEstadisticassTest(){
		List<EstadisticasDTO> list=estadisticasPersistence.getEstadisticass();
		Assert.assertEquals(list.size(), data.size());
        for(EstadisticasDTO dto:list){
        	boolean found=false;
            for(EstadisticasEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEstadisticasTest(){
		EstadisticasEntity entity=data.get(0);
		EstadisticasDTO dto=estadisticasPersistence.getEstadisticas(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getTotalInscritos(), dto.getTotalInscritos());
		Assert.assertEquals(entity.getAsistenetesTiempoReal(), dto.getAsistenetesTiempoReal());
		Assert.assertEquals(entity.getVisitasAPlataformaInscripcion(), dto.getVisitasAPlataformaInscripcion());
		Assert.assertEquals(entity.getMemoria(), dto.getMemoria());
        
	}
	
	@Test
	public void deleteEstadisticasTest(){
		EstadisticasEntity entity=data.get(0);
		estadisticasPersistence.deleteEstadisticas(entity.getId());
        EstadisticasEntity deleted=em.find(EstadisticasEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEstadisticasTest(){
		EstadisticasEntity entity=data.get(0);
		
		EstadisticasDTO dto=new EstadisticasDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setTotalInscritos(generateRandom(Integer.class));
		dto.setAsistenetesTiempoReal(generateRandom(Integer.class));
		dto.setVisitasAPlataformaInscripcion(generateRandom(Integer.class));
		dto.setMemoria(generateRandom(String.class));
		
		
		estadisticasPersistence.updateEstadisticas(dto);
		
		
		EstadisticasEntity resp=em.find(EstadisticasEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getTotalInscritos(), resp.getTotalInscritos());	
		Assert.assertEquals(dto.getAsistenetesTiempoReal(), resp.getAsistenetesTiempoReal());	
		Assert.assertEquals(dto.getVisitasAPlataformaInscripcion(), resp.getVisitasAPlataformaInscripcion());	
		Assert.assertEquals(dto.getMemoria(), resp.getMemoria());	
	}
	
	@Test
	public void getEstadisticasPaginationTest(){
		//Page 1
		EstadisticasPageDTO dto1=estadisticasPersistence.getEstadisticass(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        EstadisticasPageDTO dto2=estadisticasPersistence.getEstadisticass(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(EstadisticasDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(EstadisticasEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EstadisticasDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EstadisticasEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}