/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.coordinador.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorPageDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.logic.api._ICoordinadorLogicService;

public abstract class _CoordinadorMockLogicService implements _ICoordinadorLogicService {

	private Long id= new Long(1);
	protected List<CoordinadorDTO> data=new ArrayList<CoordinadorDTO>();

	public CoordinadorDTO createCoordinador(CoordinadorDTO coordinador){
		id++;
		coordinador.setId(id);
		data.add(coordinador);
		return coordinador;
    }
    
    public List<CoordinadorDTO> getCoordinadors(){
		return data; 
	}

	public CoordinadorPageDTO getCoordinadors(Integer page, Integer maxRecords){
		CoordinadorPageDTO response = new CoordinadorPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public CoordinadorDTO getCoordinador(Long id){
		for(CoordinadorDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteCoordinador(Long id){
	    CoordinadorDTO delete=null;
		for(CoordinadorDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateCoordinador(CoordinadorDTO coordinador){
	    CoordinadorDTO delete=null;
		for(CoordinadorDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(coordinador);
		} 
	}	
}