/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.G3xtreme.coordinador.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.api._ICoordinadorPersistence;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.converter.CoordinadorConverter;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.entity.CoordinadorEntity;

public abstract class _CoordinadorPersistence implements _ICoordinadorPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
	protected EntityManager entityManager;
	
	public CoordinadorDTO createCoordinador(CoordinadorDTO coordinador) {
		CoordinadorEntity entity=CoordinadorConverter.persistenceDTO2Entity(coordinador);
		entityManager.persist(entity);
		return CoordinadorConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<CoordinadorDTO> getCoordinadors() {
		Query q = entityManager.createQuery("select u from CoordinadorEntity u");
		return CoordinadorConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public CoordinadorDTO getCoordinador(Long id) {
		return CoordinadorConverter.entity2PersistenceDTO(entityManager.find(CoordinadorEntity.class, id));
	}

	public void deleteCoordinador(Long id) {
		CoordinadorEntity entity=entityManager.find(CoordinadorEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateCoordinador(CoordinadorDTO detail) {
		CoordinadorEntity entity=entityManager.merge(CoordinadorConverter.persistenceDTO2Entity(detail));
		CoordinadorConverter.entity2PersistenceDTO(entity);
	}

}