/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.G3xtreme.actividad.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.G3xtreme.actividad.logic.dto.ActividadDTO;
import co.edu.uniandes.csw.G3xtreme.actividad.persistence.entity.ActividadEntity;

public abstract class _ActividadConverter {

	public static ActividadDTO entity2PersistenceDTO(ActividadEntity entity){
		if (entity != null) {
			ActividadDTO dto = new ActividadDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setDescripcion(entity.getDescripcion());
					dto.setHora(entity.getHora());
					dto.setCosto(entity.getCosto());
					dto.setTema(entity.getTema());
					dto.setLugar_actividadId(entity.getLugar_actividadId());
					dto.setExpositor_actividadId(entity.getExpositor_actividadId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static ActividadEntity persistenceDTO2Entity(ActividadDTO dto){
		if(dto!=null){
			ActividadEntity entity=new ActividadEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setDescripcion(dto.getDescripcion());
			
					entity.setHora(dto.getHora());
			
					entity.setCosto(dto.getCosto());
			
					entity.setTema(dto.getTema());
			
					entity.setLugar_actividadId(dto.getLugar_actividadId());
			
					entity.setExpositor_actividadId(dto.getExpositor_actividadId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ActividadDTO> entity2PersistenceDTOList(List<ActividadEntity> entities){
		List<ActividadDTO> dtos=new ArrayList<ActividadDTO>();
		for(ActividadEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ActividadEntity> persistenceDTO2EntityList(List<ActividadDTO> dtos){
		List<ActividadEntity> entities=new ArrayList<ActividadEntity>();
		for(ActividadDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}