/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.dia.master.persistence;
import co.edu.uniandes.csw.G3xtreme.actividad.logic.dto.ActividadDTO;
import co.edu.uniandes.csw.G3xtreme.dia.master.persistence.entity.Diaactividad_diaEntity;
import co.edu.uniandes.csw.G3xtreme.actividad.persistence.converter.ActividadConverter;
import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;
import co.edu.uniandes.csw.G3xtreme.dia.master.logic.dto.DiaMasterDTO;
import co.edu.uniandes.csw.G3xtreme.dia.master.persistence.api._IDiaMasterPersistence;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.api.IDiaPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _DiaMasterPersistence implements _IDiaMasterPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IDiaPersistence diaPersistence;  

    public DiaMasterDTO getDia(Long diaId) {
        DiaMasterDTO diaMasterDTO = new DiaMasterDTO();
        DiaDTO dia = diaPersistence.getDia(diaId);
        diaMasterDTO.setDiaEntity(dia);
        diaMasterDTO.setListactividad_dia(getDiaactividad_diaEntityList(diaId));
        return diaMasterDTO;
    }

    public Diaactividad_diaEntity createDiaactividad_diaEntity(Diaactividad_diaEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteDiaactividad_diaEntity(Long diaId, Long actividad_diaId) {
        Query q = entityManager.createNamedQuery("Diaactividad_diaEntity.deleteDiaactividad_diaEntity");
        q.setParameter("diaId", diaId);
        q.setParameter("actividad_diaId", actividad_diaId);
        q.executeUpdate();
    }

    public List<ActividadDTO> getDiaactividad_diaEntityList(Long diaId) {
        ArrayList<ActividadDTO> resp = new ArrayList<ActividadDTO>();
        Query q = entityManager.createNamedQuery("Diaactividad_diaEntity.getByMasterId");
        q.setParameter("diaId",diaId);
        List<Diaactividad_diaEntity> qResult =  q.getResultList();
        for (Diaactividad_diaEntity entity : qResult) { 
            if(entity.getActividad_diaIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ActividadConverter.entity2PersistenceDTO(entity.getActividad_diaIdEntity()));
        }
        return resp;
    }

}
