/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.fase.master.persistence.entity;

import co.edu.uniandes.csw.G3xtreme.tarea.persistence.entity.TareaEntity;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.entity.FaseEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(Fasetarea_faseEntityId.class)
@NamedQueries({
    @NamedQuery(name = "Fasetarea_faseEntity.getByMasterId", query = "SELECT  u FROM Fasetarea_faseEntity u WHERE u.faseId=:faseId"),
    @NamedQuery(name = "Fasetarea_faseEntity.deleteFasetarea_faseEntity", query = "DELETE FROM Fasetarea_faseEntity u WHERE u.faseId=:faseId and  u.tarea_faseId=:tarea_faseId")
})
public class Fasetarea_faseEntity implements Serializable {

    @Id
    @Column(name = "faseId")
    private Long faseId;
    @Id
    @Column(name = "tarea_faseId")
    private Long tarea_faseId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "faseId", referencedColumnName = "id")
    @JoinFetch
    private TareaEntity faseIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "tarea_faseId", referencedColumnName = "id")
    @JoinFetch
    private TareaEntity tarea_faseIdEntity; 

    public Fasetarea_faseEntity() {
    }

    public Fasetarea_faseEntity(Long faseId, Long tarea_faseId) {
        this.faseId =faseId;
        this.tarea_faseId = tarea_faseId;
    }

    public Long getFaseId() {
        return faseId;
    }

    public void setFaseId(Long faseId) {
        this.faseId = faseId;
    }

    public Long getTarea_faseId() {
        return tarea_faseId;
    }

    public void setTarea_faseId(Long tarea_faseId) {
        this.tarea_faseId = tarea_faseId;
    }

    public TareaEntity getFaseIdEntity() {
        return faseIdEntity;
    }

    public void setFaseIdEntity(TareaEntity faseIdEntity) {
        this.faseIdEntity = faseIdEntity;
    }

    public TareaEntity getTarea_faseIdEntity() {
        return tarea_faseIdEntity;
    }

    public void setTarea_faseIdEntity(TareaEntity tarea_faseIdEntity) {
        this.tarea_faseIdEntity = tarea_faseIdEntity;
    }

}
