/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence.entity;

import co.edu.uniandes.csw.G3xtreme.empresa.persistence.entity.EmpresaEntity;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.entity.EstadisticasEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(EstadisticasempresaEntityId.class)
@NamedQueries({
    @NamedQuery(name = "EstadisticasempresaEntity.getByMasterId", query = "SELECT  u FROM EstadisticasempresaEntity u WHERE u.estadisticasId=:estadisticasId"),
    @NamedQuery(name = "EstadisticasempresaEntity.deleteEstadisticasempresaEntity", query = "DELETE FROM EstadisticasempresaEntity u WHERE u.estadisticasId=:estadisticasId and  u.empresaId=:empresaId")
})
public class EstadisticasempresaEntity implements Serializable {

    @Id
    @Column(name = "estadisticasId")
    private Long estadisticasId;
    @Id
    @Column(name = "empresaId")
    private Long empresaId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "estadisticasId", referencedColumnName = "id")
    @JoinFetch
    private EmpresaEntity estadisticasIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "empresaId", referencedColumnName = "id")
    @JoinFetch
    private EmpresaEntity empresaIdEntity; 

    public EstadisticasempresaEntity() {
    }

    public EstadisticasempresaEntity(Long estadisticasId, Long empresaId) {
        this.estadisticasId =estadisticasId;
        this.empresaId = empresaId;
    }

    public Long getEstadisticasId() {
        return estadisticasId;
    }

    public void setEstadisticasId(Long estadisticasId) {
        this.estadisticasId = estadisticasId;
    }

    public Long getEmpresaId() {
        return empresaId;
    }

    public void setEmpresaId(Long empresaId) {
        this.empresaId = empresaId;
    }

    public EmpresaEntity getEstadisticasIdEntity() {
        return estadisticasIdEntity;
    }

    public void setEstadisticasIdEntity(EmpresaEntity estadisticasIdEntity) {
        this.estadisticasIdEntity = estadisticasIdEntity;
    }

    public EmpresaEntity getEmpresaIdEntity() {
        return empresaIdEntity;
    }

    public void setEmpresaIdEntity(EmpresaEntity empresaIdEntity) {
        this.empresaIdEntity = empresaIdEntity;
    }

}
