/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence.entity;

import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence.entity.Dia_InscripcionEntity;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.entity.EstadisticasEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(Estadisticasdia_InscripcionEntityId.class)
@NamedQueries({
    @NamedQuery(name = "Estadisticasdia_InscripcionEntity.getByMasterId", query = "SELECT  u FROM Estadisticasdia_InscripcionEntity u WHERE u.estadisticasId=:estadisticasId"),
    @NamedQuery(name = "Estadisticasdia_InscripcionEntity.deleteEstadisticasdia_InscripcionEntity", query = "DELETE FROM Estadisticasdia_InscripcionEntity u WHERE u.estadisticasId=:estadisticasId and  u.dia_InscripcionId=:dia_InscripcionId")
})
public class Estadisticasdia_InscripcionEntity implements Serializable {

    @Id
    @Column(name = "estadisticasId")
    private Long estadisticasId;
    @Id
    @Column(name = "dia_InscripcionId")
    private Long dia_InscripcionId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "estadisticasId", referencedColumnName = "id")
    @JoinFetch
    private Dia_InscripcionEntity estadisticasIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "dia_InscripcionId", referencedColumnName = "id")
    @JoinFetch
    private Dia_InscripcionEntity dia_InscripcionIdEntity; 

    public Estadisticasdia_InscripcionEntity() {
    }

    public Estadisticasdia_InscripcionEntity(Long estadisticasId, Long dia_InscripcionId) {
        this.estadisticasId =estadisticasId;
        this.dia_InscripcionId = dia_InscripcionId;
    }

    public Long getEstadisticasId() {
        return estadisticasId;
    }

    public void setEstadisticasId(Long estadisticasId) {
        this.estadisticasId = estadisticasId;
    }

    public Long getDia_InscripcionId() {
        return dia_InscripcionId;
    }

    public void setDia_InscripcionId(Long dia_InscripcionId) {
        this.dia_InscripcionId = dia_InscripcionId;
    }

    public Dia_InscripcionEntity getEstadisticasIdEntity() {
        return estadisticasIdEntity;
    }

    public void setEstadisticasIdEntity(Dia_InscripcionEntity estadisticasIdEntity) {
        this.estadisticasIdEntity = estadisticasIdEntity;
    }

    public Dia_InscripcionEntity getDia_InscripcionIdEntity() {
        return dia_InscripcionIdEntity;
    }

    public void setDia_InscripcionIdEntity(Dia_InscripcionEntity dia_InscripcionIdEntity) {
        this.dia_InscripcionIdEntity = dia_InscripcionIdEntity;
    }

}
