/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.dia.master.logic.dto;

import co.edu.uniandes.csw.G3xtreme.actividad.logic.dto.ActividadDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _DiaMasterDTO {

 
    protected DiaDTO diaEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public DiaDTO getDiaEntity() {
        return diaEntity;
    }

    public void setDiaEntity(DiaDTO diaEntity) {
        this.diaEntity = diaEntity;
    }
    
    public List<ActividadDTO> createactividad_dia;
    public List<ActividadDTO> updateactividad_dia;
    public List<ActividadDTO> deleteactividad_dia;
    public List<ActividadDTO> listactividad_dia;	
	
	
	
    public List<ActividadDTO> getCreateactividad_dia(){ return createactividad_dia; };
    public void setCreateactividad_dia(List<ActividadDTO> createactividad_dia){ this.createactividad_dia=createactividad_dia; };
    public List<ActividadDTO> getUpdateactividad_dia(){ return updateactividad_dia; };
    public void setUpdateactividad_dia(List<ActividadDTO> updateactividad_dia){ this.updateactividad_dia=updateactividad_dia; };
    public List<ActividadDTO> getDeleteactividad_dia(){ return deleteactividad_dia; };
    public void setDeleteactividad_dia(List<ActividadDTO> deleteactividad_dia){ this.deleteactividad_dia=deleteactividad_dia; };
    public List<ActividadDTO> getListactividad_dia(){ return listactividad_dia; };
    public void setListactividad_dia(List<ActividadDTO> listactividad_dia){ this.listactividad_dia=listactividad_dia; };	
	
	
}

