/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.dia.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaPageDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.api.IDiaLogicService;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.DiaPersistence;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.api.IDiaPersistence;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.entity.DiaEntity;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.converter.DiaConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class DiaLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(DiaLogicService.class.getPackage())
				.addPackage(IDiaLogicService.class.getPackage())
				.addPackage(DiaPersistence.class.getPackage())
				.addPackage(DiaEntity.class.getPackage())
				.addPackage(IDiaPersistence.class.getPackage())
                .addPackage(DiaDTO.class.getPackage())
                .addPackage(DiaConverter.class.getPackage())
                .addPackage(DiaEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IDiaLogicService diaLogicService;
	
	@Inject
	private IDiaPersistence diaPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<DiaDTO> dtos=diaPersistence.getDias();
		for(DiaDTO dto:dtos){
			diaPersistence.deleteDia(dto.getId());
		}
	}

	private List<DiaDTO> data=new ArrayList<DiaDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			DiaDTO pdto=new DiaDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setFecha(generateRandomDate());
			pdto.setCosto(generateRandom(Long.class));
			pdto=diaPersistence.createDia(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createDiaTest(){
		DiaDTO ldto=new DiaDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setFecha(generateRandomDate());
		ldto.setCosto(generateRandom(Long.class));
		
		
		DiaDTO result=diaLogicService.createDia(ldto);
		
		Assert.assertNotNull(result);
		
		DiaDTO pdto=diaPersistence.getDia(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getFecha(), pdto.getFecha());	
		Assert.assertEquals(ldto.getCosto(), pdto.getCosto());	
	}
	
	@Test
	public void getDiasTest(){
		List<DiaDTO> list=diaLogicService.getDias();
		Assert.assertEquals(list.size(), data.size());
        for(DiaDTO ldto:list){
        	boolean found=false;
            for(DiaDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getDiaTest(){
		DiaDTO pdto=data.get(0);
		DiaDTO ldto=diaLogicService.getDia(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getFecha(), ldto.getFecha());
		Assert.assertEquals(pdto.getCosto(), ldto.getCosto());
        
	}
	
	@Test
	public void deleteDiaTest(){
		DiaDTO pdto=data.get(0);
		diaLogicService.deleteDia(pdto.getId());
        DiaDTO deleted=diaPersistence.getDia(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateDiaTest(){
		DiaDTO pdto=data.get(0);
		
		DiaDTO ldto=new DiaDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setFecha(generateRandomDate());
		ldto.setCosto(generateRandom(Long.class));
		
		
		diaLogicService.updateDia(ldto);
		
		
		DiaDTO resp=diaPersistence.getDia(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getFecha(), resp.getFecha());	
		Assert.assertEquals(ldto.getCosto(), resp.getCosto());	
	}
	
	@Test
	public void getDiaPaginationTest(){
		
		DiaPageDTO dto1=diaLogicService.getDias(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		DiaPageDTO dto2=diaLogicService.getDias(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(DiaDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(DiaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(DiaDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(DiaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        DiaPageDTO dto3=diaLogicService.getDias(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(DiaDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(DiaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}