/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.dia.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.api.IDiaLogicService;
import co.edu.uniandes.csw.G3xtreme.dia.master.logic.api._IDiaMasterLogicService;
import co.edu.uniandes.csw.G3xtreme.dia.master.logic.dto.DiaMasterDTO;
import co.edu.uniandes.csw.G3xtreme.actividad.logic.api.IActividadLogicService;
import co.edu.uniandes.csw.G3xtreme.actividad.logic.dto.ActividadDTO;
import javax.inject.Inject;


public abstract class _DiaMasterMockLogicService implements _IDiaMasterLogicService {

    protected static ArrayList<DiaMasterDTO> diaMasterDtosList = new ArrayList<DiaMasterDTO>() ;
    @Inject
    protected IActividadLogicService actividadPersistance;
    @Inject
    protected IDiaLogicService diaPersistance;

    public DiaMasterDTO createMasterDia(DiaMasterDTO dia) {

        diaPersistance.createDia(dia.getDiaEntity());
        for (ActividadDTO dto : dia.getCreateactividad_dia()) {
            actividadPersistance.createActividad(dto);
        }
        diaMasterDtosList.add(dia);
        return dia;
    }

    public DiaMasterDTO getMasterDia(Long id) {
        for (DiaMasterDTO diaMasterDTO : diaMasterDtosList) {
            if (diaMasterDTO.getDiaEntity().getId() == id) {
                return diaMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterDia(Long id) {
        for (DiaMasterDTO diaMasterDTO : diaMasterDtosList) {
            if (diaMasterDTO.getDiaEntity().getId() == id) {

                for (ActividadDTO dto : diaMasterDTO.getCreateactividad_dia()) {
                    actividadPersistance.deleteActividad(dto.getId());
                }
                diaPersistance.deleteDia(diaMasterDTO.getId());
                diaMasterDtosList.remove(diaMasterDTO);
            }
        }

    }

    public void updateMasterDia(DiaMasterDTO dia) {

        // update Actividad
        if (dia.getUpdateactividad_dia() != null) {
            for (ActividadDTO dto : dia.getUpdateactividad_dia()) {
                actividadPersistance.updateActividad(dto);
            }
        }
        // persist new Actividad
        if (dia.getCreateactividad_dia() != null) {
            for (ActividadDTO dto : dia.getCreateactividad_dia()) {
                ActividadDTO persistedActividadDTO = actividadPersistance.createActividad(dto);
                dto = persistedActividadDTO;
            }
        }
        // delete Actividad
        if (dia.getDeleteactividad_dia() != null) {
            for (ActividadDTO dto : dia.getDeleteactividad_dia()) {

                actividadPersistance.deleteActividad(dto.getId());
            }
        }
    }
}