/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.foro.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.foro.logic.dto.ForoPageDTO;
import co.edu.uniandes.csw.G3xtreme.foro.logic.dto.ForoDTO;
import co.edu.uniandes.csw.G3xtreme.foro.persistence.api.IForoPersistence;
import co.edu.uniandes.csw.G3xtreme.foro.persistence.entity.ForoEntity;
import co.edu.uniandes.csw.G3xtreme.foro.persistence.converter.ForoConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ForoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ForoPersistence.class.getPackage())
				.addPackage(ForoEntity.class.getPackage())
				.addPackage(IForoPersistence.class.getPackage())
                .addPackage(ForoDTO.class.getPackage())
                .addPackage(ForoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IForoPersistence foroPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ForoEntity").executeUpdate();
	}

	private List<ForoEntity> data=new ArrayList<ForoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ForoEntity entity=new ForoEntity();
			entity.setName(generateRandom(String.class));
			entity.setTema(generateRandom(String.class));
			entity.setPresupuesto(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createForoTest(){
		ForoDTO dto=new ForoDTO();
		dto.setName(generateRandom(String.class));
		dto.setTema(generateRandom(String.class));
		dto.setPresupuesto(generateRandom(Long.class));
		
		ForoDTO result=foroPersistence.createForo(dto);
		
		Assert.assertNotNull(result);
		
		ForoEntity entity=em.find(ForoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getTema(), entity.getTema());
		Assert.assertEquals(dto.getPresupuesto(), entity.getPresupuesto());
	}
	
	@Test
	public void getForosTest(){
		List<ForoDTO> list=foroPersistence.getForos();
		Assert.assertEquals(list.size(), data.size());
        for(ForoDTO dto:list){
        	boolean found=false;
            for(ForoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getForoTest(){
		ForoEntity entity=data.get(0);
		ForoDTO dto=foroPersistence.getForo(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getTema(), dto.getTema());
		Assert.assertEquals(entity.getPresupuesto(), dto.getPresupuesto());
        
	}
	
	@Test
	public void deleteForoTest(){
		ForoEntity entity=data.get(0);
		foroPersistence.deleteForo(entity.getId());
        ForoEntity deleted=em.find(ForoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateForoTest(){
		ForoEntity entity=data.get(0);
		
		ForoDTO dto=new ForoDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setTema(generateRandom(String.class));
		dto.setPresupuesto(generateRandom(Long.class));
		
		
		foroPersistence.updateForo(dto);
		
		
		ForoEntity resp=em.find(ForoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getTema(), resp.getTema());	
		Assert.assertEquals(dto.getPresupuesto(), resp.getPresupuesto());	
	}
	
	@Test
	public void getForoPaginationTest(){
		//Page 1
		ForoPageDTO dto1=foroPersistence.getForos(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ForoPageDTO dto2=foroPersistence.getForos(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ForoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ForoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ForoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ForoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}