/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.lugar.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.G3xtreme.lugar.logic.dto.LugarDTO;
import co.edu.uniandes.csw.G3xtreme.lugar.logic.dto.LugarPageDTO;
import co.edu.uniandes.csw.G3xtreme.lugar.logic.api._ILugarLogicService;
import co.edu.uniandes.csw.G3xtreme.lugar.persistence.api.ILugarPersistence;

public abstract class _LugarLogicService implements _ILugarLogicService {

	@Inject
	protected ILugarPersistence persistance;

	public LugarDTO createLugar(LugarDTO lugar){
		return persistance.createLugar( lugar); 
    }

	public List<LugarDTO> getLugars(){
		return persistance.getLugars(); 
	}

	public LugarPageDTO getLugars(Integer page, Integer maxRecords){
		return persistance.getLugars(page, maxRecords); 
	}

	public LugarDTO getLugar(Long id){
		return persistance.getLugar(id); 
	}

	public void deleteLugar(Long id){
	    persistance.deleteLugar(id); 
	}

	public void updateLugar(LugarDTO lugar){
	    persistance.updateLugar(lugar); 
	}	
}