/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionPageDTO;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionDTO;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence.api.IDia_InscripcionPersistence;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence.entity.Dia_InscripcionEntity;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence.converter.Dia_InscripcionConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class Dia_InscripcionPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(Dia_InscripcionPersistence.class.getPackage())
				.addPackage(Dia_InscripcionEntity.class.getPackage())
				.addPackage(IDia_InscripcionPersistence.class.getPackage())
                .addPackage(Dia_InscripcionDTO.class.getPackage())
                .addPackage(Dia_InscripcionConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IDia_InscripcionPersistence dia_InscripcionPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from Dia_InscripcionEntity").executeUpdate();
	}

	private List<Dia_InscripcionEntity> data=new ArrayList<Dia_InscripcionEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			Dia_InscripcionEntity entity=new Dia_InscripcionEntity();
			entity.setName(generateRandom(String.class));
			entity.setFecha(generateRandom(Date.class));
			entity.setNumInscritos(generateRandom(Integer.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createDia_InscripcionTest(){
		Dia_InscripcionDTO dto=new Dia_InscripcionDTO();
		dto.setName(generateRandom(String.class));
dto.setFecha(generateRandomDate());
		dto.setNumInscritos(generateRandom(Integer.class));
		
		Dia_InscripcionDTO result=dia_InscripcionPersistence.createDia_Inscripcion(dto);
		
		Assert.assertNotNull(result);
		
		Dia_InscripcionEntity entity=em.find(Dia_InscripcionEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
Assert.assertEquals(parseDate(dto.getFecha()), entity.getFecha());	
		Assert.assertEquals(dto.getNumInscritos(), entity.getNumInscritos());
	}
	
	@Test
	public void getDia_InscripcionsTest(){
		List<Dia_InscripcionDTO> list=dia_InscripcionPersistence.getDia_Inscripcions();
		Assert.assertEquals(list.size(), data.size());
        for(Dia_InscripcionDTO dto:list){
        	boolean found=false;
            for(Dia_InscripcionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getDia_InscripcionTest(){
		Dia_InscripcionEntity entity=data.get(0);
		Dia_InscripcionDTO dto=dia_InscripcionPersistence.getDia_Inscripcion(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getNumInscritos(), dto.getNumInscritos());
        
	}
	
	@Test
	public void deleteDia_InscripcionTest(){
		Dia_InscripcionEntity entity=data.get(0);
		dia_InscripcionPersistence.deleteDia_Inscripcion(entity.getId());
        Dia_InscripcionEntity deleted=em.find(Dia_InscripcionEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateDia_InscripcionTest(){
		Dia_InscripcionEntity entity=data.get(0);
		
		Dia_InscripcionDTO dto=new Dia_InscripcionDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
dto.setFecha(generateRandomDate());
		dto.setNumInscritos(generateRandom(Integer.class));
		
		
		dia_InscripcionPersistence.updateDia_Inscripcion(dto);
		
		
		Dia_InscripcionEntity resp=em.find(Dia_InscripcionEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
Assert.assertEquals(parseDate(dto.getFecha()), resp.getFecha());
		Assert.assertEquals(dto.getNumInscritos(), resp.getNumInscritos());	
	}
	
	@Test
	public void getDia_InscripcionPaginationTest(){
		//Page 1
		Dia_InscripcionPageDTO dto1=dia_InscripcionPersistence.getDia_Inscripcions(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        Dia_InscripcionPageDTO dto2=dia_InscripcionPersistence.getDia_Inscripcions(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(Dia_InscripcionDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(Dia_InscripcionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(Dia_InscripcionDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(Dia_InscripcionEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}