/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.coordinador.master.persistence.entity;

import co.edu.uniandes.csw.G3xtreme.tarea.persistence.entity.TareaEntity;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.entity.CoordinadorEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(Coordinadortarea_coordinadorEntityId.class)
@NamedQueries({
    @NamedQuery(name = "Coordinadortarea_coordinadorEntity.getByMasterId", query = "SELECT  u FROM Coordinadortarea_coordinadorEntity u WHERE u.coordinadorId=:coordinadorId"),
    @NamedQuery(name = "Coordinadortarea_coordinadorEntity.deleteCoordinadortarea_coordinadorEntity", query = "DELETE FROM Coordinadortarea_coordinadorEntity u WHERE u.coordinadorId=:coordinadorId and  u.tarea_coordinadorId=:tarea_coordinadorId")
})
public class Coordinadortarea_coordinadorEntity implements Serializable {

    @Id
    @Column(name = "coordinadorId")
    private Long coordinadorId;
    @Id
    @Column(name = "tarea_coordinadorId")
    private Long tarea_coordinadorId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "coordinadorId", referencedColumnName = "id")
    @JoinFetch
    private TareaEntity coordinadorIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "tarea_coordinadorId", referencedColumnName = "id")
    @JoinFetch
    private TareaEntity tarea_coordinadorIdEntity; 

    public Coordinadortarea_coordinadorEntity() {
    }

    public Coordinadortarea_coordinadorEntity(Long coordinadorId, Long tarea_coordinadorId) {
        this.coordinadorId =coordinadorId;
        this.tarea_coordinadorId = tarea_coordinadorId;
    }

    public Long getCoordinadorId() {
        return coordinadorId;
    }

    public void setCoordinadorId(Long coordinadorId) {
        this.coordinadorId = coordinadorId;
    }

    public Long getTarea_coordinadorId() {
        return tarea_coordinadorId;
    }

    public void setTarea_coordinadorId(Long tarea_coordinadorId) {
        this.tarea_coordinadorId = tarea_coordinadorId;
    }

    public TareaEntity getCoordinadorIdEntity() {
        return coordinadorIdEntity;
    }

    public void setCoordinadorIdEntity(TareaEntity coordinadorIdEntity) {
        this.coordinadorIdEntity = coordinadorIdEntity;
    }

    public TareaEntity getTarea_coordinadorIdEntity() {
        return tarea_coordinadorIdEntity;
    }

    public void setTarea_coordinadorIdEntity(TareaEntity tarea_coordinadorIdEntity) {
        this.tarea_coordinadorIdEntity = tarea_coordinadorIdEntity;
    }

}
