/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.dia.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaPageDTO;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.api._IDiaPersistence;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.converter.DiaConverter;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.entity.DiaEntity;

public abstract class _DiaPersistence implements _IDiaPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
	protected EntityManager entityManager;
	
	public DiaDTO createDia(DiaDTO dia) {
		DiaEntity entity=DiaConverter.persistenceDTO2Entity(dia);
		entityManager.persist(entity);
		return DiaConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<DiaDTO> getDias() {
		Query q = entityManager.createQuery("select u from DiaEntity u");
		return DiaConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public DiaPageDTO getDias(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from DiaEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from DiaEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		DiaPageDTO response = new DiaPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(DiaConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public DiaDTO getDia(Long id) {
		return DiaConverter.entity2PersistenceDTO(entityManager.find(DiaEntity.class, id));
	}

	public void deleteDia(Long id) {
		DiaEntity entity=entityManager.find(DiaEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateDia(DiaDTO detail) {
		DiaEntity entity=entityManager.merge(DiaConverter.persistenceDTO2Entity(detail));
		DiaConverter.entity2PersistenceDTO(entity);
	}

}