/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.foro.master.persistence.api;

import co.edu.uniandes.csw.G3xtreme.foro.master.persistence.entity.Forofase_foroEntity;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.foro.master.persistence.entity.Forocoordinador_foroEntity;
import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorDTO;
import co.edu.uniandes.csw.G3xtreme.foro.master.persistence.entity.Forodia_foroEntity;
import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;
import co.edu.uniandes.csw.G3xtreme.foro.master.logic.dto.ForoMasterDTO;
import java.util.List;

public interface _IForoMasterPersistence {

	public ForoMasterDTO getForo(Long foroId);
	
	
    public Forofase_foroEntity createForofase_foroEntity(Forofase_foroEntity entity);
    public void deleteForofase_foroEntity(Long foroId, Long fase_foroId);
    public List<FaseDTO> getForofase_foroEntityList(Long foroId);
    public Forocoordinador_foroEntity createForocoordinador_foroEntity(Forocoordinador_foroEntity entity);
    public void deleteForocoordinador_foroEntity(Long foroId, Long coordinador_foroId);
    public List<CoordinadorDTO> getForocoordinador_foroEntityList(Long foroId);
    public Forodia_foroEntity createForodia_foroEntity(Forodia_foroEntity entity);
    public void deleteForodia_foroEntity(Long foroId, Long dia_foroId);
    public List<DiaDTO> getForodia_foroEntityList(Long foroId);
   
  
}
