/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionDTO;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionPageDTO;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.api._IDia_InscripcionLogicService;

public abstract class _Dia_InscripcionMockLogicService implements _IDia_InscripcionLogicService {

	private Long id= new Long(1);
	protected List<Dia_InscripcionDTO> data=new ArrayList<Dia_InscripcionDTO>();

	public Dia_InscripcionDTO createDia_Inscripcion(Dia_InscripcionDTO dia_Inscripcion){
		id++;
		dia_Inscripcion.setId(id);
		data.add(dia_Inscripcion);
		return dia_Inscripcion;
    }
    
    public List<Dia_InscripcionDTO> getDia_Inscripcions(){
		return data; 
	}

	public Dia_InscripcionPageDTO getDia_Inscripcions(Integer page, Integer maxRecords){
		Dia_InscripcionPageDTO response = new Dia_InscripcionPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public Dia_InscripcionDTO getDia_Inscripcion(Long id){
		for(Dia_InscripcionDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteDia_Inscripcion(Long id){
	    Dia_InscripcionDTO delete=null;
		for(Dia_InscripcionDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateDia_Inscripcion(Dia_InscripcionDTO dia_Inscripcion){
	    Dia_InscripcionDTO delete=null;
		for(Dia_InscripcionDTO data1:data){
			if(data1.getId().equals(dia_Inscripcion.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(dia_Inscripcion);
		} 
	}	
}