/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.fase.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FasePageDTO;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.api.IFasePersistence;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.entity.FaseEntity;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.converter.FaseConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class FasePersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(FasePersistence.class.getPackage())
				.addPackage(FaseEntity.class.getPackage())
				.addPackage(IFasePersistence.class.getPackage())
                .addPackage(FaseDTO.class.getPackage())
                .addPackage(FaseConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IFasePersistence fasePersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from FaseEntity").executeUpdate();
	}

	private List<FaseEntity> data=new ArrayList<FaseEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			FaseEntity entity=new FaseEntity();
			entity.setName(generateRandom(String.class));
			entity.setEstado(generateRandom(Boolean.class));
			entity.setFechaInicio(generateRandom(Date.class));
			entity.setFechaFin(generateRandom(Date.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createFaseTest(){
		FaseDTO dto=new FaseDTO();
		dto.setName(generateRandom(String.class));
		dto.setEstado(generateRandom(Boolean.class));
dto.setFechaInicio(generateRandomDate());
dto.setFechaFin(generateRandomDate());
		
		FaseDTO result=fasePersistence.createFase(dto);
		
		Assert.assertNotNull(result);
		
		FaseEntity entity=em.find(FaseEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getEstado(), entity.getEstado());
Assert.assertEquals(parseDate(dto.getFechaInicio()), entity.getFechaInicio());	
Assert.assertEquals(parseDate(dto.getFechaFin()), entity.getFechaFin());	
	}
	
	@Test
	public void getFasesTest(){
		List<FaseDTO> list=fasePersistence.getFases();
		Assert.assertEquals(list.size(), data.size());
        for(FaseDTO dto:list){
        	boolean found=false;
            for(FaseEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getFaseTest(){
		FaseEntity entity=data.get(0);
		FaseDTO dto=fasePersistence.getFase(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getEstado(), dto.getEstado());
        
	}
	
	@Test
	public void deleteFaseTest(){
		FaseEntity entity=data.get(0);
		fasePersistence.deleteFase(entity.getId());
        FaseEntity deleted=em.find(FaseEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateFaseTest(){
		FaseEntity entity=data.get(0);
		
		FaseDTO dto=new FaseDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setEstado(generateRandom(Boolean.class));
dto.setFechaInicio(generateRandomDate());
dto.setFechaFin(generateRandomDate());
		
		
		fasePersistence.updateFase(dto);
		
		
		FaseEntity resp=em.find(FaseEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getEstado(), resp.getEstado());	
Assert.assertEquals(parseDate(dto.getFechaInicio()), resp.getFechaInicio());
Assert.assertEquals(parseDate(dto.getFechaFin()), resp.getFechaFin());
	}
	
	@Test
	public void getFasePaginationTest(){
		//Page 1
		FasePageDTO dto1=fasePersistence.getFases(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        FasePageDTO dto2=fasePersistence.getFases(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(FaseDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(FaseEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(FaseDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(FaseEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}