/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.coordinador.master.logic.dto;

import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _CoordinadorMasterDTO {

 
    protected CoordinadorDTO coordinadorEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public CoordinadorDTO getCoordinadorEntity() {
        return coordinadorEntity;
    }

    public void setCoordinadorEntity(CoordinadorDTO coordinadorEntity) {
        this.coordinadorEntity = coordinadorEntity;
    }
    
    public List<TareaDTO> createtarea_coordinador;
    public List<TareaDTO> updatetarea_coordinador;
    public List<TareaDTO> deletetarea_coordinador;
    public List<TareaDTO> listtarea_coordinador;	
	
	
	
    public List<TareaDTO> getCreatetarea_coordinador(){ return createtarea_coordinador; };
    public void setCreatetarea_coordinador(List<TareaDTO> createtarea_coordinador){ this.createtarea_coordinador=createtarea_coordinador; };
    public List<TareaDTO> getUpdatetarea_coordinador(){ return updatetarea_coordinador; };
    public void setUpdatetarea_coordinador(List<TareaDTO> updatetarea_coordinador){ this.updatetarea_coordinador=updatetarea_coordinador; };
    public List<TareaDTO> getDeletetarea_coordinador(){ return deletetarea_coordinador; };
    public void setDeletetarea_coordinador(List<TareaDTO> deletetarea_coordinador){ this.deletetarea_coordinador=deletetarea_coordinador; };
    public List<TareaDTO> getListtarea_coordinador(){ return listtarea_coordinador; };
    public void setListtarea_coordinador(List<TareaDTO> listtarea_coordinador){ this.listtarea_coordinador=listtarea_coordinador; };	
	
	
}

