/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/
define(['model/_estadisticasModel'], function() {
    App.Model.EstadisticasModel = App.Model._EstadisticasModel.extend({

 		validate: function(attrs,options){
            var validationMessage = "";
            if(!attrs.name){
                validationMessage = "El nombre no puede estar vacio";
            }
            if(!attrs.totalInscritos)
            {
                validationMessage = "El total de inscritos no puede estar vacío";
            }
            else
            {
                try{
                var n=parseInt(attrs.totalInscritos);
                if(n<0)
                {
                    validationMessage = "El total de inscritos no puede ser negativo";
                }
            }catch(e){
                validationMessage = "El total de inscritos debe ser un número";
            }
            }
            if(!attrs.asistentesTiempoReal)
            {
                validationMessage = "El total de asistentes no puede estar vacío";
            }
            else
            {
                try{
                var n=parseInt(attrs.asistentesTiempoReal);
                if(n<0)
                {
                    validationMessage = "El total de asistentes no puede ser negativo";
                }
            }catch(e){
                validationMessage = "El total de asistentes debe ser un número";
            }
            }
            if(!attrs.visitasAPlataformaInscripcion)
            {
                validationMessage = "El total de visitas no puede estar vacío";
            }
            else
            {
                try{
                var n=parseInt(attrs.visitasAPlataformaInscripcion);
                if(n<0)
                {
                    validationMessage = "El total de visitas no puede ser negativo";
                }
            }catch(e){
                validationMessage = "El total de visitas debe ser un número";
            }
            }
            if(!attrs.memoria)
            {
                validationMessage = "La memoria no puede estar vacía";
            }
            else
            {
                try{
                var n=parseInt(attrs.memoria);
                if(n<0)
                {
                    validationMessage = "El total de memoria no puede ser negativo";
                }
            }catch(e){
                validationMessage = "El total de memoria debe ser un número";
            }
            }
            if(validationMessage.length>0){
               return validationMessage;
            }
        }

    });

    App.Model.EstadisticasList = App.Model._EstadisticasList.extend({
        model: App.Model.EstadisticasModel
    });

    return  App.Model.EstadisticasModel;

});