/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.estadisticas.master.logic.dto;

import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionDTO;
import co.edu.uniandes.csw.G3xtreme.empresa.logic.dto.EmpresaDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.logic.dto.EstadisticasDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _EstadisticasMasterDTO {

 
    protected EstadisticasDTO estadisticasEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public EstadisticasDTO getEstadisticasEntity() {
        return estadisticasEntity;
    }

    public void setEstadisticasEntity(EstadisticasDTO estadisticasEntity) {
        this.estadisticasEntity = estadisticasEntity;
    }
    
    public List<Dia_InscripcionDTO> createdia_Inscripcion;
    public List<Dia_InscripcionDTO> updatedia_Inscripcion;
    public List<Dia_InscripcionDTO> deletedia_Inscripcion;
    public List<Dia_InscripcionDTO> listdia_Inscripcion;	
    public List<EmpresaDTO> createempresa;
    public List<EmpresaDTO> updateempresa;
    public List<EmpresaDTO> deleteempresa;
    public List<EmpresaDTO> listempresa;	
	
	
	
    public List<Dia_InscripcionDTO> getCreatedia_Inscripcion(){ return createdia_Inscripcion; };
    public void setCreatedia_Inscripcion(List<Dia_InscripcionDTO> createdia_Inscripcion){ this.createdia_Inscripcion=createdia_Inscripcion; };
    public List<Dia_InscripcionDTO> getUpdatedia_Inscripcion(){ return updatedia_Inscripcion; };
    public void setUpdatedia_Inscripcion(List<Dia_InscripcionDTO> updatedia_Inscripcion){ this.updatedia_Inscripcion=updatedia_Inscripcion; };
    public List<Dia_InscripcionDTO> getDeletedia_Inscripcion(){ return deletedia_Inscripcion; };
    public void setDeletedia_Inscripcion(List<Dia_InscripcionDTO> deletedia_Inscripcion){ this.deletedia_Inscripcion=deletedia_Inscripcion; };
    public List<Dia_InscripcionDTO> getListdia_Inscripcion(){ return listdia_Inscripcion; };
    public void setListdia_Inscripcion(List<Dia_InscripcionDTO> listdia_Inscripcion){ this.listdia_Inscripcion=listdia_Inscripcion; };	
    public List<EmpresaDTO> getCreateempresa(){ return createempresa; };
    public void setCreateempresa(List<EmpresaDTO> createempresa){ this.createempresa=createempresa; };
    public List<EmpresaDTO> getUpdateempresa(){ return updateempresa; };
    public void setUpdateempresa(List<EmpresaDTO> updateempresa){ this.updateempresa=updateempresa; };
    public List<EmpresaDTO> getDeleteempresa(){ return deleteempresa; };
    public void setDeleteempresa(List<EmpresaDTO> deleteempresa){ this.deleteempresa=deleteempresa; };
    public List<EmpresaDTO> getListempresa(){ return listempresa; };
    public void setListempresa(List<EmpresaDTO> listempresa){ this.listempresa=listempresa; };	
	
	
}

