/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.responsable.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.responsable.logic.dto.ResponsablePageDTO;
import co.edu.uniandes.csw.G3xtreme.responsable.logic.dto.ResponsableDTO;
import co.edu.uniandes.csw.G3xtreme.responsable.persistence.api.IResponsablePersistence;
import co.edu.uniandes.csw.G3xtreme.responsable.persistence.entity.ResponsableEntity;
import co.edu.uniandes.csw.G3xtreme.responsable.persistence.converter.ResponsableConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ResponsablePersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ResponsablePersistence.class.getPackage())
				.addPackage(ResponsableEntity.class.getPackage())
				.addPackage(IResponsablePersistence.class.getPackage())
                .addPackage(ResponsableDTO.class.getPackage())
                .addPackage(ResponsableConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IResponsablePersistence responsablePersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ResponsableEntity").executeUpdate();
	}

	private List<ResponsableEntity> data=new ArrayList<ResponsableEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ResponsableEntity entity=new ResponsableEntity();
			entity.setName(generateRandom(String.class));
			entity.setCorreo(generateRandom(String.class));
			entity.setTipo(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createResponsableTest(){
		ResponsableDTO dto=new ResponsableDTO();
		dto.setName(generateRandom(String.class));
		dto.setCorreo(generateRandom(String.class));
		dto.setTipo(generateRandom(String.class));
		
		ResponsableDTO result=responsablePersistence.createResponsable(dto);
		
		Assert.assertNotNull(result);
		
		ResponsableEntity entity=em.find(ResponsableEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getCorreo(), entity.getCorreo());
		Assert.assertEquals(dto.getTipo(), entity.getTipo());
	}
	
	@Test
	public void getResponsablesTest(){
		List<ResponsableDTO> list=responsablePersistence.getResponsables();
		Assert.assertEquals(list.size(), data.size());
        for(ResponsableDTO dto:list){
        	boolean found=false;
            for(ResponsableEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getResponsableTest(){
		ResponsableEntity entity=data.get(0);
		ResponsableDTO dto=responsablePersistence.getResponsable(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getCorreo(), dto.getCorreo());
		Assert.assertEquals(entity.getTipo(), dto.getTipo());
        
	}
	
	@Test
	public void deleteResponsableTest(){
		ResponsableEntity entity=data.get(0);
		responsablePersistence.deleteResponsable(entity.getId());
        ResponsableEntity deleted=em.find(ResponsableEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateResponsableTest(){
		ResponsableEntity entity=data.get(0);
		
		ResponsableDTO dto=new ResponsableDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setCorreo(generateRandom(String.class));
		dto.setTipo(generateRandom(String.class));
		
		
		responsablePersistence.updateResponsable(dto);
		
		
		ResponsableEntity resp=em.find(ResponsableEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getCorreo(), resp.getCorreo());	
		Assert.assertEquals(dto.getTipo(), resp.getTipo());	
	}
	
	@Test
	public void getResponsablePaginationTest(){
		//Page 1
		ResponsablePageDTO dto1=responsablePersistence.getResponsables(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ResponsablePageDTO dto2=responsablePersistence.getResponsables(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ResponsableDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ResponsableEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ResponsableDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ResponsableEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}