/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.coordinador.master.persistence;
import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.master.persistence.entity.Coordinadortarea_coordinadorEntity;
import co.edu.uniandes.csw.G3xtreme.tarea.persistence.converter.TareaConverter;
import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.master.logic.dto.CoordinadorMasterDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.master.persistence.api._ICoordinadorMasterPersistence;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.api.ICoordinadorPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _CoordinadorMasterPersistence implements _ICoordinadorMasterPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected ICoordinadorPersistence coordinadorPersistence;  

    public CoordinadorMasterDTO getCoordinador(Long coordinadorId) {
        CoordinadorMasterDTO coordinadorMasterDTO = new CoordinadorMasterDTO();
        CoordinadorDTO coordinador = coordinadorPersistence.getCoordinador(coordinadorId);
        coordinadorMasterDTO.setCoordinadorEntity(coordinador);
        coordinadorMasterDTO.setListtarea_coordinador(getCoordinadortarea_coordinadorEntityList(coordinadorId));
        return coordinadorMasterDTO;
    }

    public Coordinadortarea_coordinadorEntity createCoordinadortarea_coordinadorEntity(Coordinadortarea_coordinadorEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteCoordinadortarea_coordinadorEntity(Long coordinadorId, Long tarea_coordinadorId) {
        Query q = entityManager.createNamedQuery("Coordinadortarea_coordinadorEntity.deleteCoordinadortarea_coordinadorEntity");
        q.setParameter("coordinadorId", coordinadorId);
        q.setParameter("tarea_coordinadorId", tarea_coordinadorId);
        q.executeUpdate();
    }

    public List<TareaDTO> getCoordinadortarea_coordinadorEntityList(Long coordinadorId) {
        ArrayList<TareaDTO> resp = new ArrayList<TareaDTO>();
        Query q = entityManager.createNamedQuery("Coordinadortarea_coordinadorEntity.getByMasterId");
        q.setParameter("coordinadorId",coordinadorId);
        List<Coordinadortarea_coordinadorEntity> qResult =  q.getResultList();
        for (Coordinadortarea_coordinadorEntity entity : qResult) { 
            if(entity.getTarea_coordinadorIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(TareaConverter.entity2PersistenceDTO(entity.getTarea_coordinadorIdEntity()));
        }
        return resp;
    }

}
