/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.expositor.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G3xtreme.expositor.logic.dto.ExpositorDTO;
import co.edu.uniandes.csw.G3xtreme.expositor.logic.dto.ExpositorPageDTO;
import co.edu.uniandes.csw.G3xtreme.expositor.logic.api._IExpositorLogicService;

public abstract class _ExpositorMockLogicService implements _IExpositorLogicService {

	private Long id= new Long(1);
	protected List<ExpositorDTO> data=new ArrayList<ExpositorDTO>();

	public ExpositorDTO createExpositor(ExpositorDTO expositor){
		id++;
		expositor.setId(id);
		data.add(expositor);
		return expositor;
    }
    
    public List<ExpositorDTO> getExpositors(){
		return data; 
	}

	public ExpositorPageDTO getExpositors(Integer page, Integer maxRecords){
		ExpositorPageDTO response = new ExpositorPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public ExpositorDTO getExpositor(Long id){
		for(ExpositorDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteExpositor(Long id){
	    ExpositorDTO delete=null;
		for(ExpositorDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateExpositor(ExpositorDTO expositor){
	    ExpositorDTO delete=null;
		for(ExpositorDTO data1:data){
			if(data1.getId().equals(expositor.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(expositor);
		} 
	}	
}