/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.fase.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.fase.logic.api.IFaseLogicService;
import co.edu.uniandes.csw.G3xtreme.fase.master.logic.api._IFaseMasterLogicService;
import co.edu.uniandes.csw.G3xtreme.fase.master.logic.dto.FaseMasterDTO;
import co.edu.uniandes.csw.G3xtreme.tarea.logic.api.ITareaLogicService;
import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaDTO;
import javax.inject.Inject;


public abstract class _FaseMasterMockLogicService implements _IFaseMasterLogicService {

    protected static ArrayList<FaseMasterDTO> faseMasterDtosList = new ArrayList<FaseMasterDTO>() ;
    @Inject
    protected ITareaLogicService tareaPersistance;
    @Inject
    protected IFaseLogicService fasePersistance;

    public FaseMasterDTO createMasterFase(FaseMasterDTO fase) {

        fasePersistance.createFase(fase.getFaseEntity());
        for (TareaDTO dto : fase.getCreatetarea_fase()) {
            fase.getListtarea_fase().add(tareaPersistance.createTarea(dto));
        }
        faseMasterDtosList.add(fase);
        return fase;
    }

    public FaseMasterDTO getMasterFase(Long id) {
        for (FaseMasterDTO faseMasterDTO : faseMasterDtosList) {
            if (faseMasterDTO.getFaseEntity().getId() == id) {
                return faseMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterFase(Long id) {
        for (FaseMasterDTO faseMasterDTO : faseMasterDtosList) {
            if (faseMasterDTO.getFaseEntity().getId() == id) {

                for (TareaDTO dto : faseMasterDTO.getCreatetarea_fase()) {
                    tareaPersistance.deleteTarea(dto.getId());
                }
                fasePersistance.deleteFase(faseMasterDTO.getId());
                faseMasterDtosList.remove(faseMasterDTO);
            }
        }

    }

    public void updateMasterFase(FaseMasterDTO fase) {

		FaseMasterDTO currentFase = getMasterFase(fase.getFaseEntity().getId());
		if (currentFase == null) {
			currentFase = fase;
		}else{
			faseMasterDtosList.remove(currentFase);
		}

        // update Tarea
        if (fase.getUpdatetarea_fase() != null) {
            for (TareaDTO dto : fase.getUpdatetarea_fase()) {
                tareaPersistance.updateTarea(dto);
                for (TareaDTO tareadto : currentFase.getListtarea_fase()) {
					if (tareadto.getId() == dto.getId()) {
						currentFase.getListtarea_fase().remove(tareadto);
						currentFase.getListtarea_fase().add(dto);
					}
				}
            }
        }
        // persist new Tarea
        if (fase.getCreatetarea_fase() != null) {
            for (TareaDTO dto : fase.getCreatetarea_fase()) {
                TareaDTO persistedTareaDTO = tareaPersistance.createTarea(dto);
                dto = persistedTareaDTO;
                currentFase.getListtarea_fase().add(dto);
            }
        }
        // delete Tarea
        if (fase.getDeletetarea_fase() != null) {
            for (TareaDTO dto : fase.getDeletetarea_fase()) {
				for (TareaDTO tareadto : currentFase.getListtarea_fase()) {
					if (tareadto.getId() == dto.getId()) {
						currentFase.getListtarea_fase().remove(tareadto);
					}
				}
                tareaPersistance.deleteTarea(dto.getId());
            }
        }
        faseMasterDtosList.add(currentFase);
    }
}