 

   ALTER TABLE APP.Forofase_foroEntity ADD FOREIGN KEY (foroId) REFERENCES  APP.ForoEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
   ALTER TABLE APP.Forofase_foroEntity ADD FOREIGN KEY (fase_foroId) REFERENCES  APP.FaseEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
   ALTER TABLE APP.ForoactividadEntity ADD FOREIGN KEY (foroId) REFERENCES  APP.ForoEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
   ALTER TABLE APP.ForoactividadEntity ADD FOREIGN KEY (actividadId) REFERENCES  APP.ActividadEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
		
   ALTER TABLE APP.Fasetarea_faseEntity ADD FOREIGN KEY (faseId) REFERENCES  APP.FaseEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
   ALTER TABLE APP.Fasetarea_faseEntity ADD FOREIGN KEY (tarea_faseId) REFERENCES  APP.TareaEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
		
   ALTER TABLE APP.Estadisticasdia_InscripcionEntity ADD FOREIGN KEY (estadisticasId) REFERENCES  APP.EstadisticasEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
   ALTER TABLE APP.Estadisticasdia_InscripcionEntity ADD FOREIGN KEY (dia_InscripcionId) REFERENCES  APP.Dia_InscripcionEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
   ALTER TABLE APP.EstadisticasempresaEntity ADD FOREIGN KEY (estadisticasId) REFERENCES  APP.EstadisticasEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
   ALTER TABLE APP.EstadisticasempresaEntity ADD FOREIGN KEY (empresaId) REFERENCES  APP.EmpresaEntity(id) ON DELETE CASCADE ON UPDATE RESTRICT;
		
