/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.fase.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FasePageDTO;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.api._IFasePersistence;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.converter.FaseConverter;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.entity.FaseEntity;

public abstract class _FasePersistence implements _IFasePersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
	protected EntityManager entityManager;
	
	public FaseDTO createFase(FaseDTO fase) {
		FaseEntity entity=FaseConverter.persistenceDTO2Entity(fase);
		entityManager.persist(entity);
		return FaseConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<FaseDTO> getFases() {
		Query q = entityManager.createQuery("select u from FaseEntity u");
		return FaseConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public FasePageDTO getFases(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from FaseEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from FaseEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		FasePageDTO response = new FasePageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(FaseConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public FaseDTO getFase(Long id) {
		return FaseConverter.entity2PersistenceDTO(entityManager.find(FaseEntity.class, id));
	}

	public void deleteFase(Long id) {
		FaseEntity entity=entityManager.find(FaseEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateFase(FaseDTO detail) {
		FaseEntity entity=entityManager.merge(FaseConverter.persistenceDTO2Entity(detail));
		FaseConverter.entity2PersistenceDTO(entity);
	}

}