/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.tarea.logic.dto;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement 
public abstract class _TareaDTO {

	

	private Long id;
	

	private String name;
	

	private String responsable;
	

	private String fechaInicio;
	

	private String fechaFin;
	

	private String descripcion;
	

	private Integer estado;
	

	private Long responsable_tareaId;



	public Long getId() {
		return id;
	}
 
	public void setId(Long id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}
 
	public void setName(String name) {
		this.name = name;
	}


	public String getResponsable() {
		return responsable;
	}
 
	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}


	public String getFechaInicio() {
		return fechaInicio;
	}
 
	public void setFechaInicio(String fechainicio) {
		this.fechaInicio = fechainicio;
	}


	public String getFechaFin() {
		return fechaFin;
	}
 
	public void setFechaFin(String fechafin) {
		this.fechaFin = fechafin;
	}


	public String getDescripcion() {
		return descripcion;
	}
 
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	public Integer getEstado() {
		return estado;
	}
 
	public void setEstado(Integer estado) {
		this.estado = estado;
	}


	public Long getResponsable_tareaId() {
		return responsable_tareaId;
	}
 
	public void setResponsable_tareaId(Long responsable_tareaid) {
		this.responsable_tareaId = responsable_tareaid;
	}
	
}