/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.empresa.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.empresa.logic.dto.EmpresaPageDTO;
import co.edu.uniandes.csw.G3xtreme.empresa.logic.dto.EmpresaDTO;
import co.edu.uniandes.csw.G3xtreme.empresa.persistence.api.IEmpresaPersistence;
import co.edu.uniandes.csw.G3xtreme.empresa.persistence.entity.EmpresaEntity;
import co.edu.uniandes.csw.G3xtreme.empresa.persistence.converter.EmpresaConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EmpresaPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EmpresaPersistence.class.getPackage())
				.addPackage(EmpresaEntity.class.getPackage())
				.addPackage(IEmpresaPersistence.class.getPackage())
                .addPackage(EmpresaDTO.class.getPackage())
                .addPackage(EmpresaConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEmpresaPersistence empresaPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EmpresaEntity").executeUpdate();
	}

	private List<EmpresaEntity> data=new ArrayList<EmpresaEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EmpresaEntity entity=new EmpresaEntity();
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEmpresaTest(){
		EmpresaDTO dto=new EmpresaDTO();
		dto.setName(generateRandom(String.class));
		
		EmpresaDTO result=empresaPersistence.createEmpresa(dto);
		
		Assert.assertNotNull(result);
		
		EmpresaEntity entity=em.find(EmpresaEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getEmpresasTest(){
		List<EmpresaDTO> list=empresaPersistence.getEmpresas();
		Assert.assertEquals(list.size(), data.size());
        for(EmpresaDTO dto:list){
        	boolean found=false;
            for(EmpresaEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEmpresaTest(){
		EmpresaEntity entity=data.get(0);
		EmpresaDTO dto=empresaPersistence.getEmpresa(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteEmpresaTest(){
		EmpresaEntity entity=data.get(0);
		empresaPersistence.deleteEmpresa(entity.getId());
        EmpresaEntity deleted=em.find(EmpresaEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEmpresaTest(){
		EmpresaEntity entity=data.get(0);
		
		EmpresaDTO dto=new EmpresaDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		
		
		empresaPersistence.updateEmpresa(dto);
		
		
		EmpresaEntity resp=em.find(EmpresaEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
	
	@Test
	public void getEmpresaPaginationTest(){
		//Page 1
		EmpresaPageDTO dto1=empresaPersistence.getEmpresas(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        EmpresaPageDTO dto2=empresaPersistence.getEmpresas(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(EmpresaDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(EmpresaEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EmpresaDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EmpresaEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}