/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.G3xtreme.coordinador.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.entity.CoordinadorEntity;

public abstract class _CoordinadorConverter {

	public static CoordinadorDTO entity2PersistenceDTO(CoordinadorEntity entity){
		if (entity != null) {
			CoordinadorDTO dto = new CoordinadorDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setCorreo(entity.getCorreo());
			return dto;
		}else{
			return null;
		}
	}
	
	public static CoordinadorEntity persistenceDTO2Entity(CoordinadorDTO dto){
		if(dto!=null){
			CoordinadorEntity entity=new CoordinadorEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setCorreo(dto.getCorreo());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<CoordinadorDTO> entity2PersistenceDTOList(List<CoordinadorEntity> entities){
		List<CoordinadorDTO> dtos=new ArrayList<CoordinadorDTO>();
		for(CoordinadorEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<CoordinadorEntity> persistenceDTO2EntityList(List<CoordinadorDTO> dtos){
		List<CoordinadorEntity> entities=new ArrayList<CoordinadorEntity>();
		for(CoordinadorDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}