/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.dia.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaPageDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.api._IDiaLogicService;
import co.edu.uniandes.csw.G3xtreme.dia.persistence.api.IDiaPersistence;

public abstract class _DiaLogicService implements _IDiaLogicService {

	@Inject
	protected IDiaPersistence persistance;

	public DiaDTO createDia(DiaDTO dia){
		return persistance.createDia( dia); 
    }

	public List<DiaDTO> getDias(){
		return persistance.getDias(); 
	}

	public DiaPageDTO getDias(Integer page, Integer maxRecords){
		return persistance.getDias(page, maxRecords); 
	}

	public DiaDTO getDia(Long id){
		return persistance.getDia(id); 
	}

	public void deleteDia(Long id){
	    persistance.deleteDia(id); 
	}

	public void updateDia(DiaDTO dia){
	    persistance.updateDia(dia); 
	}	
}