/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.tarea.logic.ejb;

import co.edu.uniandes.csw.G3xtreme.info.logic.dto.InfoDTO;
import javax.ejb.EJB;
import javax.ejb.LocalBean;
import javax.ejb.Stateless; 
import javax.inject.Inject;

import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.G3xtreme.tarea.logic.api.ITareaLogicService;
import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaDTO;
import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaPageDTO;

@Default
@Stateless
@LocalBean
public class TareaLogicService extends _TareaLogicService implements ITareaLogicService {

    public TareaPageDTO getTareasByFase(String idFase) {
       return persistance.getTareasByFase(idFase);
    }

    
    public TareaPageDTO getTareasAll(String nombreForo) {
        return persistance.getTareasAll(nombreForo);
    }

    public TareaPageDTO getTareasPorResponsable(String responsable) {
        return persistance.getTareasResponsable(responsable);
    }
    

     public InfoDTO updateEstadoTarea(long id, String idTarea, String valor) {
        return persistance.updateEstadoTarea(id,idTarea,valor);
    }

    public TareaDTO crearTarea(TareaDTO nueva, String idFase) {
         return persistance.creartarea(nueva,idFase); //To change body of generated methods, choose Tools | Templates.
    }
}
