/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.foro.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G3xtreme.foro.logic.dto.ForoDTO;
import co.edu.uniandes.csw.G3xtreme.foro.logic.dto.ForoPageDTO;
import co.edu.uniandes.csw.G3xtreme.foro.persistence.api._IForoPersistence;
import co.edu.uniandes.csw.G3xtreme.foro.persistence.converter.ForoConverter;
import co.edu.uniandes.csw.G3xtreme.foro.persistence.entity.ForoEntity;

public abstract class _ForoPersistence implements _IForoPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
	protected EntityManager entityManager;
	
	public ForoDTO createForo(ForoDTO foro) {
		ForoEntity entity=ForoConverter.persistenceDTO2Entity(foro);
		entityManager.persist(entity);
		return ForoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ForoDTO> getForos() {
		Query q = entityManager.createQuery("select u from ForoEntity u");
		return ForoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ForoPageDTO getForos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ForoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ForoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ForoPageDTO response = new ForoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ForoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ForoDTO getForo(Long id) {
		return ForoConverter.entity2PersistenceDTO(entityManager.find(ForoEntity.class, id));
	}

	public void deleteForo(Long id) {
		ForoEntity entity=entityManager.find(ForoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateForo(ForoDTO detail) {
		ForoEntity entity=entityManager.merge(ForoConverter.persistenceDTO2Entity(detail));
		ForoConverter.entity2PersistenceDTO(entity);
	}

}