/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.foro.persistence;

import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaPageDTO;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FasePageDTO;
import co.edu.uniandes.csw.G3xtreme.foro.persistence.api.IForoPersistence;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class ForoPersistence extends _ForoPersistence  implements IForoPersistence {
    

    public FasePageDTO getFasesByForo(String idForo, Integer page, Integer maxRecords) {
       String query = "select * from FASEENTITY where FOROFASE_FOROENTITY.foroid = "+idForo+" and FOROFASE_FOROENTITY.fase_foroId = FASEENTITY.ID";
        Query q = entityManager.createNativeQuery(query);
        List<Object[]> lista = q.getResultList();
        FasePageDTO resp= new FasePageDTO();
        List<FaseDTO> fases= new ArrayList<FaseDTO>();
        for(int i=0;i<lista.size();i++){
            Object actual[] = lista.get(i);
            FaseDTO faseActual = new FaseDTO();
            faseActual.setId((Long)actual[0]);
            faseActual.setEstado((Integer)actual[1]);
            faseActual.setFechaFin(((Date)actual[2]).toString());
            faseActual.setFechaInicio(((Date)actual[3]).toString());
            faseActual.setName((String)actual[4]);
            fases.add(faseActual);
        }
        resp.setRecords(fases);
        return resp;
    }

    public DiaPageDTO getDiasByForo(String idForo) {
        String query = "select * from DIAENTITY where FORODIA_FOROENTITY.foroid = "+idForo+" and FORODIA_FOROENTITY.dia_foroId = DIAENTITY.ID";
        Query q = entityManager.createNativeQuery(query);
        List<Object[]> lista = q.getResultList();
        DiaPageDTO resp= new DiaPageDTO();
        List<DiaDTO> dias= new ArrayList<DiaDTO>();
        for(int i=0;i<lista.size();i++){
            Object actual[] = lista.get(i);
            DiaDTO diaActual = new DiaDTO();
            diaActual.setFecha(((Date)actual[0]).toString());
            diaActual.setCosto((Long)actual[1]);   
            dias.add(diaActual);
        }
        resp.setRecords(dias);
        return resp;
    }

}