/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.estadisticas.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.estadisticas.logic.dto.EstadisticasPageDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.logic.dto.EstadisticasDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.logic.api.IEstadisticasLogicService;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.EstadisticasPersistence;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.api.IEstadisticasPersistence;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.entity.EstadisticasEntity;
import co.edu.uniandes.csw.G3xtreme.estadisticas.persistence.converter.EstadisticasConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EstadisticasLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EstadisticasLogicService.class.getPackage())
				.addPackage(IEstadisticasLogicService.class.getPackage())
				.addPackage(EstadisticasPersistence.class.getPackage())
				.addPackage(EstadisticasEntity.class.getPackage())
				.addPackage(IEstadisticasPersistence.class.getPackage())
                .addPackage(EstadisticasDTO.class.getPackage())
                .addPackage(EstadisticasConverter.class.getPackage())
                .addPackage(EstadisticasEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEstadisticasLogicService estadisticasLogicService;
	
	@Inject
	private IEstadisticasPersistence estadisticasPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<EstadisticasDTO> dtos=estadisticasPersistence.getEstadisticass();
		for(EstadisticasDTO dto:dtos){
			estadisticasPersistence.deleteEstadisticas(dto.getId());
		}
	}

	private List<EstadisticasDTO> data=new ArrayList<EstadisticasDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EstadisticasDTO pdto=new EstadisticasDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setTotalInscritos(generateRandom(Integer.class));
			pdto.setAsistenetesTiempoReal(generateRandom(Integer.class));
			pdto.setVisitasAPlataformaInscripcion(generateRandom(Integer.class));
			pdto.setMemoria(generateRandom(String.class));
			pdto=estadisticasPersistence.createEstadisticas(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createEstadisticasTest(){
		EstadisticasDTO ldto=new EstadisticasDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setTotalInscritos(generateRandom(Integer.class));
		ldto.setAsistenetesTiempoReal(generateRandom(Integer.class));
		ldto.setVisitasAPlataformaInscripcion(generateRandom(Integer.class));
		ldto.setMemoria(generateRandom(String.class));
		
		
		EstadisticasDTO result=estadisticasLogicService.createEstadisticas(ldto);
		
		Assert.assertNotNull(result);
		
		EstadisticasDTO pdto=estadisticasPersistence.getEstadisticas(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getTotalInscritos(), pdto.getTotalInscritos());	
		Assert.assertEquals(ldto.getAsistenetesTiempoReal(), pdto.getAsistenetesTiempoReal());	
		Assert.assertEquals(ldto.getVisitasAPlataformaInscripcion(), pdto.getVisitasAPlataformaInscripcion());	
		Assert.assertEquals(ldto.getMemoria(), pdto.getMemoria());	
	}
	
	@Test
	public void getEstadisticassTest(){
		List<EstadisticasDTO> list=estadisticasLogicService.getEstadisticass();
		Assert.assertEquals(list.size(), data.size());
        for(EstadisticasDTO ldto:list){
        	boolean found=false;
            for(EstadisticasDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEstadisticasTest(){
		EstadisticasDTO pdto=data.get(0);
		EstadisticasDTO ldto=estadisticasLogicService.getEstadisticas(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getTotalInscritos(), ldto.getTotalInscritos());
		Assert.assertEquals(pdto.getAsistenetesTiempoReal(), ldto.getAsistenetesTiempoReal());
		Assert.assertEquals(pdto.getVisitasAPlataformaInscripcion(), ldto.getVisitasAPlataformaInscripcion());
		Assert.assertEquals(pdto.getMemoria(), ldto.getMemoria());
        
	}
	
	@Test
	public void deleteEstadisticasTest(){
		EstadisticasDTO pdto=data.get(0);
		estadisticasLogicService.deleteEstadisticas(pdto.getId());
        EstadisticasDTO deleted=estadisticasPersistence.getEstadisticas(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEstadisticasTest(){
		EstadisticasDTO pdto=data.get(0);
		
		EstadisticasDTO ldto=new EstadisticasDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setTotalInscritos(generateRandom(Integer.class));
		ldto.setAsistenetesTiempoReal(generateRandom(Integer.class));
		ldto.setVisitasAPlataformaInscripcion(generateRandom(Integer.class));
		ldto.setMemoria(generateRandom(String.class));
		
		
		estadisticasLogicService.updateEstadisticas(ldto);
		
		
		EstadisticasDTO resp=estadisticasPersistence.getEstadisticas(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getTotalInscritos(), resp.getTotalInscritos());	
		Assert.assertEquals(ldto.getAsistenetesTiempoReal(), resp.getAsistenetesTiempoReal());	
		Assert.assertEquals(ldto.getVisitasAPlataformaInscripcion(), resp.getVisitasAPlataformaInscripcion());	
		Assert.assertEquals(ldto.getMemoria(), resp.getMemoria());	
	}
	
	@Test
	public void getEstadisticasPaginationTest(){
		
		EstadisticasPageDTO dto1=estadisticasLogicService.getEstadisticass(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		EstadisticasPageDTO dto2=estadisticasLogicService.getEstadisticass(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(EstadisticasDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(EstadisticasDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EstadisticasDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EstadisticasDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        EstadisticasPageDTO dto3=estadisticasLogicService.getEstadisticass(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(EstadisticasDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(EstadisticasDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}