/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.empresa.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.empresa.logic.dto.EmpresaPageDTO;
import co.edu.uniandes.csw.G3xtreme.empresa.logic.dto.EmpresaDTO;
import co.edu.uniandes.csw.G3xtreme.empresa.logic.api.IEmpresaLogicService;
import co.edu.uniandes.csw.G3xtreme.empresa.persistence.EmpresaPersistence;
import co.edu.uniandes.csw.G3xtreme.empresa.persistence.api.IEmpresaPersistence;
import co.edu.uniandes.csw.G3xtreme.empresa.persistence.entity.EmpresaEntity;
import co.edu.uniandes.csw.G3xtreme.empresa.persistence.converter.EmpresaConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EmpresaLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EmpresaLogicService.class.getPackage())
				.addPackage(IEmpresaLogicService.class.getPackage())
				.addPackage(EmpresaPersistence.class.getPackage())
				.addPackage(EmpresaEntity.class.getPackage())
				.addPackage(IEmpresaPersistence.class.getPackage())
                .addPackage(EmpresaDTO.class.getPackage())
                .addPackage(EmpresaConverter.class.getPackage())
                .addPackage(EmpresaEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEmpresaLogicService empresaLogicService;
	
	@Inject
	private IEmpresaPersistence empresaPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<EmpresaDTO> dtos=empresaPersistence.getEmpresas();
		for(EmpresaDTO dto:dtos){
			empresaPersistence.deleteEmpresa(dto.getId());
		}
	}

	private List<EmpresaDTO> data=new ArrayList<EmpresaDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EmpresaDTO pdto=new EmpresaDTO();
			pdto.setName(generateRandom(String.class));
			pdto=empresaPersistence.createEmpresa(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createEmpresaTest(){
		EmpresaDTO ldto=new EmpresaDTO();
		ldto.setName(generateRandom(String.class));
		
		
		EmpresaDTO result=empresaLogicService.createEmpresa(ldto);
		
		Assert.assertNotNull(result);
		
		EmpresaDTO pdto=empresaPersistence.getEmpresa(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
	}
	
	@Test
	public void getEmpresasTest(){
		List<EmpresaDTO> list=empresaLogicService.getEmpresas();
		Assert.assertEquals(list.size(), data.size());
        for(EmpresaDTO ldto:list){
        	boolean found=false;
            for(EmpresaDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEmpresaTest(){
		EmpresaDTO pdto=data.get(0);
		EmpresaDTO ldto=empresaLogicService.getEmpresa(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
        
	}
	
	@Test
	public void deleteEmpresaTest(){
		EmpresaDTO pdto=data.get(0);
		empresaLogicService.deleteEmpresa(pdto.getId());
        EmpresaDTO deleted=empresaPersistence.getEmpresa(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEmpresaTest(){
		EmpresaDTO pdto=data.get(0);
		
		EmpresaDTO ldto=new EmpresaDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		
		
		empresaLogicService.updateEmpresa(ldto);
		
		
		EmpresaDTO resp=empresaPersistence.getEmpresa(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
	}
	
	@Test
	public void getEmpresaPaginationTest(){
		
		EmpresaPageDTO dto1=empresaLogicService.getEmpresas(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		EmpresaPageDTO dto2=empresaLogicService.getEmpresas(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(EmpresaDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(EmpresaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EmpresaDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EmpresaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        EmpresaPageDTO dto3=empresaLogicService.getEmpresas(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(EmpresaDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(EmpresaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}