/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.G3xtreme.fase.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.entity.FaseEntity;

public abstract class _FaseConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static FaseDTO entity2PersistenceDTO(FaseEntity entity){
		if (entity != null) {
			FaseDTO dto = new FaseDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setEstado(entity.getEstado());
 
			    if(entity.getFechaInicio() != null){
					dto.setFechaInicio(DATE_FORMAT.format(entity.getFechaInicio()));
				}	
 
			    if(entity.getFechaFin() != null){
					dto.setFechaFin(DATE_FORMAT.format(entity.getFechaFin()));
				}	
			return dto;
		}else{
			return null;
		}
	}
	
	public static FaseEntity persistenceDTO2Entity(FaseDTO dto){
		if(dto!=null){
			FaseEntity entity=new FaseEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setEstado(dto.getEstado());
			
 
			      try{ 
			        if(dto.getFechaInicio() != null){
						entity.setFechaInicio(DATE_FORMAT.parse(dto.getFechaInicio()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_FaseConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
 
			      try{ 
			        if(dto.getFechaFin() != null){
						entity.setFechaFin(DATE_FORMAT.parse(dto.getFechaFin()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_FaseConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<FaseDTO> entity2PersistenceDTOList(List<FaseEntity> entities){
		List<FaseDTO> dtos=new ArrayList<FaseDTO>();
		for(FaseEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<FaseEntity> persistenceDTO2EntityList(List<FaseDTO> dtos){
		List<FaseEntity> entities=new ArrayList<FaseEntity>();
		for(FaseDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}