/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.coordinador.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorPageDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.api.ICoordinadorPersistence;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.entity.CoordinadorEntity;
import co.edu.uniandes.csw.G3xtreme.coordinador.persistence.converter.CoordinadorConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class CoordinadorPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(CoordinadorPersistence.class.getPackage())
				.addPackage(CoordinadorEntity.class.getPackage())
				.addPackage(ICoordinadorPersistence.class.getPackage())
                .addPackage(CoordinadorDTO.class.getPackage())
                .addPackage(CoordinadorConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ICoordinadorPersistence coordinadorPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from CoordinadorEntity").executeUpdate();
	}

	private List<CoordinadorEntity> data=new ArrayList<CoordinadorEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			CoordinadorEntity entity=new CoordinadorEntity();
			entity.setName(generateRandom(String.class));
			entity.setCorreo(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createCoordinadorTest(){
		CoordinadorDTO dto=new CoordinadorDTO();
		dto.setName(generateRandom(String.class));
		dto.setCorreo(generateRandom(String.class));
		
		CoordinadorDTO result=coordinadorPersistence.createCoordinador(dto);
		
		Assert.assertNotNull(result);
		
		CoordinadorEntity entity=em.find(CoordinadorEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getCorreo(), entity.getCorreo());
	}
	
	@Test
	public void getCoordinadorsTest(){
		List<CoordinadorDTO> list=coordinadorPersistence.getCoordinadors();
		Assert.assertEquals(list.size(), data.size());
        for(CoordinadorDTO dto:list){
        	boolean found=false;
            for(CoordinadorEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getCoordinadorTest(){
		CoordinadorEntity entity=data.get(0);
		CoordinadorDTO dto=coordinadorPersistence.getCoordinador(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getCorreo(), dto.getCorreo());
        
	}
	
	@Test
	public void deleteCoordinadorTest(){
		CoordinadorEntity entity=data.get(0);
		coordinadorPersistence.deleteCoordinador(entity.getId());
        CoordinadorEntity deleted=em.find(CoordinadorEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateCoordinadorTest(){
		CoordinadorEntity entity=data.get(0);
		
		CoordinadorDTO dto=new CoordinadorDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setCorreo(generateRandom(String.class));
		
		
		coordinadorPersistence.updateCoordinador(dto);
		
		
		CoordinadorEntity resp=em.find(CoordinadorEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getCorreo(), resp.getCorreo());	
	}
	
	@Test
	public void getCoordinadorPaginationTest(){
		//Page 1
		CoordinadorPageDTO dto1=coordinadorPersistence.getCoordinadors(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        CoordinadorPageDTO dto2=coordinadorPersistence.getCoordinadors(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(CoordinadorDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(CoordinadorEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(CoordinadorDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(CoordinadorEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}