/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.G3xtreme.tarea.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaDTO;
import co.edu.uniandes.csw.G3xtreme.tarea.persistence.api._ITareaPersistence;
import co.edu.uniandes.csw.G3xtreme.tarea.persistence.converter.TareaConverter;
import co.edu.uniandes.csw.G3xtreme.tarea.persistence.entity.TareaEntity;

public abstract class _TareaPersistence implements _ITareaPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
	protected EntityManager entityManager;
	
	public TareaDTO createTarea(TareaDTO tarea) {
		TareaEntity entity=TareaConverter.persistenceDTO2Entity(tarea);
		entityManager.persist(entity);
		return TareaConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<TareaDTO> getTareas() {
		Query q = entityManager.createQuery("select u from TareaEntity u");
		return TareaConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public TareaDTO getTarea(Long id) {
		return TareaConverter.entity2PersistenceDTO(entityManager.find(TareaEntity.class, id));
	}

	public void deleteTarea(Long id) {
		TareaEntity entity=entityManager.find(TareaEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateTarea(TareaDTO detail) {
		TareaEntity entity=entityManager.merge(TareaConverter.persistenceDTO2Entity(detail));
		TareaConverter.entity2PersistenceDTO(entity);
	}

}