/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.G3xtreme.actividad.logic.dto;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement 
public abstract class _ActividadDTO {

	

	private Long id;
	

	private String name;
	

	private String descripcion;
	

	private Long hora;
	

	private Long costo;
	

	private String tema;
	

	private Long lugar_actividadId;
	

	private Long expositor_actividadId;



	public Long getId() {
		return id;
	}
 
	public void setId(Long id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}
 
	public void setName(String name) {
		this.name = name;
	}


	public String getDescripcion() {
		return descripcion;
	}
 
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	public Long getHora() {
		return hora;
	}
 
	public void setHora(Long hora) {
		this.hora = hora;
	}


	public Long getCosto() {
		return costo;
	}
 
	public void setCosto(Long costo) {
		this.costo = costo;
	}


	public String getTema() {
		return tema;
	}
 
	public void setTema(String tema) {
		this.tema = tema;
	}


	public Long getLugar_actividadId() {
		return lugar_actividadId;
	}
 
	public void setLugar_actividadId(Long lugar_actividadid) {
		this.lugar_actividadId = lugar_actividadid;
	}


	public Long getExpositor_actividadId() {
		return expositor_actividadId;
	}
 
	public void setExpositor_actividadId(Long expositor_actividadid) {
		this.expositor_actividadId = expositor_actividadid;
	}
	
}