/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.G3xtreme.fase.service;

import co.edu.uniandes.csw.G3xtreme.fase.logic.api.IFaseLogicService;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FasePageDTO;
import co.edu.uniandes.csw.G3xtreme.info.logic.dto.InfoDTO;
import java.util.ArrayList;
import co.edu.uniandes.csw.G3xtreme.info.logic.dto.InfoPageDTO;
import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaDTO;
import java.util.List;
import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.core.UriInfo;

@Path("/Fase")
@Stateless
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class FaseService extends _FaseService {
    
          
        @Context
        UriInfo uriInfo;
        
        @GET
        @Path("estado")
        public List getEstadosFaseforo(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords){
		//return faseLogicService.getFases(page, maxRecords);
            return null;
	}
        
        @GET
        @Override
        @Path("/getFasesByForo")
        public FasePageDTO getFases(@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords) {
         //Implementar lógica de búsqueda
         MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
         String idForo = queryParams.getFirst("idForo");
         System.out.println("el di es: " + idForo);
        return faseLogicService.getFasesByForo(idForo);
     }
        
        @GET
        @Path("/getTareasPorFase")
        public ArrayList<TareaDTO> getTareasPorFase(){
             MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
             String idForo = queryParams.getFirst("idForo");
             String numFase = queryParams.getFirst("numFase");
             
             ArrayList resp = new ArrayList();
             
             //agregar a resp los TareaDTO
             
             return resp;
        }
        
        public InfoDTO getEstadoFasesForo(@PathParam("id") Long id){
            //MultivaluedMap<String, String> queryParams = uriInfo.getQueryParameters();
            //System.out.println("Llega1");
            List<Integer> resp = faseLogicService.getEstadoFasesForo(id);
            //System.out.println(uriInfo.getPathParameters());
            InfoDTO r= new InfoDTO();
            r.setListaComas(resp.toString());
            return r;
           
        }
}
