/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.foro.master.logic.dto;

import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.actividad.logic.dto.ActividadDTO;
import co.edu.uniandes.csw.G3xtreme.foro.logic.dto.ForoDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _ForoMasterDTO {

 
    protected ForoDTO foroEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public ForoDTO getForoEntity() {
        return foroEntity;
    }

    public void setForoEntity(ForoDTO foroEntity) {
        this.foroEntity = foroEntity;
    }
    
    public List<FaseDTO> createfase_foro;
    public List<FaseDTO> updatefase_foro;
    public List<FaseDTO> deletefase_foro;
    public List<FaseDTO> listfase_foro;	
    public List<ActividadDTO> createactividad;
    public List<ActividadDTO> updateactividad;
    public List<ActividadDTO> deleteactividad;
    public List<ActividadDTO> listactividad;	
	
	
	
    public List<FaseDTO> getCreatefase_foro(){ return createfase_foro; };
    public void setCreatefase_foro(List<FaseDTO> createfase_foro){ this.createfase_foro=createfase_foro; };
    public List<FaseDTO> getUpdatefase_foro(){ return updatefase_foro; };
    public void setUpdatefase_foro(List<FaseDTO> updatefase_foro){ this.updatefase_foro=updatefase_foro; };
    public List<FaseDTO> getDeletefase_foro(){ return deletefase_foro; };
    public void setDeletefase_foro(List<FaseDTO> deletefase_foro){ this.deletefase_foro=deletefase_foro; };
    public List<FaseDTO> getListfase_foro(){ return listfase_foro; };
    public void setListfase_foro(List<FaseDTO> listfase_foro){ this.listfase_foro=listfase_foro; };	
    public List<ActividadDTO> getCreateactividad(){ return createactividad; };
    public void setCreateactividad(List<ActividadDTO> createactividad){ this.createactividad=createactividad; };
    public List<ActividadDTO> getUpdateactividad(){ return updateactividad; };
    public void setUpdateactividad(List<ActividadDTO> updateactividad){ this.updateactividad=updateactividad; };
    public List<ActividadDTO> getDeleteactividad(){ return deleteactividad; };
    public void setDeleteactividad(List<ActividadDTO> deleteactividad){ this.deleteactividad=deleteactividad; };
    public List<ActividadDTO> getListactividad(){ return listactividad; };
    public void setListactividad(List<ActividadDTO> listactividad){ this.listactividad=listactividad; };	
	
	
}

