/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionDTO;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence.entity.Dia_InscripcionEntity;

public abstract class _Dia_InscripcionConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static Dia_InscripcionDTO entity2PersistenceDTO(Dia_InscripcionEntity entity){
		if (entity != null) {
			Dia_InscripcionDTO dto = new Dia_InscripcionDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
 
			    if(entity.getFecha() != null){
					dto.setFecha(DATE_FORMAT.format(entity.getFecha()));
				}	
					dto.setNumInscritos(entity.getNumInscritos());
			return dto;
		}else{
			return null;
		}
	}
	
	public static Dia_InscripcionEntity persistenceDTO2Entity(Dia_InscripcionDTO dto){
		if(dto!=null){
			Dia_InscripcionEntity entity=new Dia_InscripcionEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
 
			      try{ 
			        if(dto.getFecha() != null){
						entity.setFecha(DATE_FORMAT.parse(dto.getFecha()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_Dia_InscripcionConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setNumInscritos(dto.getNumInscritos());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<Dia_InscripcionDTO> entity2PersistenceDTOList(List<Dia_InscripcionEntity> entities){
		List<Dia_InscripcionDTO> dtos=new ArrayList<Dia_InscripcionDTO>();
		for(Dia_InscripcionEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<Dia_InscripcionEntity> persistenceDTO2EntityList(List<Dia_InscripcionDTO> dtos){
		List<Dia_InscripcionEntity> entities=new ArrayList<Dia_InscripcionEntity>();
		for(Dia_InscripcionDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}