/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.fase.master.persistence;
import co.edu.uniandes.csw.G3xtreme.tarea.logic.dto.TareaDTO;
import co.edu.uniandes.csw.G3xtreme.fase.master.persistence.entity.Fasetarea_faseEntity;
import co.edu.uniandes.csw.G3xtreme.tarea.persistence.converter.TareaConverter;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import co.edu.uniandes.csw.G3xtreme.fase.master.logic.dto.FaseMasterDTO;
import co.edu.uniandes.csw.G3xtreme.fase.master.persistence.api._IFaseMasterPersistence;
import co.edu.uniandes.csw.G3xtreme.fase.persistence.api.IFasePersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _FaseMasterPersistence implements _IFaseMasterPersistence {

  	@PersistenceContext(unitName="ForosISISPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IFasePersistence fasePersistence;  

    public FaseMasterDTO getFase(Long faseId) {
        FaseMasterDTO faseMasterDTO = new FaseMasterDTO();
        FaseDTO fase = fasePersistence.getFase(faseId);
        faseMasterDTO.setFaseEntity(fase);
        faseMasterDTO.setListtarea_fase(getFasetarea_faseEntityList(faseId));
        return faseMasterDTO;
    }

    public Fasetarea_faseEntity createFasetarea_faseEntity(Fasetarea_faseEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteFasetarea_faseEntity(Long faseId, Long tarea_faseId) {
        Query q = entityManager.createNamedQuery("Fasetarea_faseEntity.deleteFasetarea_faseEntity");
        q.setParameter("faseId", faseId);
        q.setParameter("tarea_faseId", tarea_faseId);
        q.executeUpdate();
    }

    public List<TareaDTO> getFasetarea_faseEntityList(Long faseId) {
        ArrayList<TareaDTO> resp = new ArrayList<TareaDTO>();
        Query q = entityManager.createNamedQuery("Fasetarea_faseEntity.getByMasterId");
        q.setParameter("faseId",faseId);
        List<Fasetarea_faseEntity> qResult =  q.getResultList();
        for (Fasetarea_faseEntity entity : qResult) { 
            if(entity.getTarea_faseIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(TareaConverter.entity2PersistenceDTO(entity.getTarea_faseIdEntity()));
        }
        return resp;
    }

}
