/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.actividad.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.actividad.logic.dto.ActividadPageDTO;
import co.edu.uniandes.csw.G3xtreme.actividad.logic.dto.ActividadDTO;
import co.edu.uniandes.csw.G3xtreme.actividad.persistence.api.IActividadPersistence;
import co.edu.uniandes.csw.G3xtreme.actividad.persistence.entity.ActividadEntity;
import co.edu.uniandes.csw.G3xtreme.actividad.persistence.converter.ActividadConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ActividadPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ActividadPersistence.class.getPackage())
				.addPackage(ActividadEntity.class.getPackage())
				.addPackage(IActividadPersistence.class.getPackage())
                .addPackage(ActividadDTO.class.getPackage())
                .addPackage(ActividadConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IActividadPersistence actividadPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ActividadEntity").executeUpdate();
	}

	private List<ActividadEntity> data=new ArrayList<ActividadEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ActividadEntity entity=new ActividadEntity();
			entity.setName(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setCosto(generateRandom(Long.class));
			entity.setFecha(generateRandom(Date.class));
			entity.setHora(generateRandom(String.class));
			entity.setLugar_actividadId(generateRandom(Long.class));
			entity.setExpositor_actividadId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createActividadTest(){
		ActividadDTO dto=new ActividadDTO();
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setCosto(generateRandom(Long.class));
dto.setFecha(generateRandomDate());
		dto.setHora(generateRandom(String.class));
		dto.setLugar_actividadId(generateRandom(Long.class));
		dto.setExpositor_actividadId(generateRandom(Long.class));
		
		ActividadDTO result=actividadPersistence.createActividad(dto);
		
		Assert.assertNotNull(result);
		
		ActividadEntity entity=em.find(ActividadEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getCosto(), entity.getCosto());
Assert.assertEquals(parseDate(dto.getFecha()), entity.getFecha());	
		Assert.assertEquals(dto.getHora(), entity.getHora());
		Assert.assertEquals(dto.getLugar_actividadId(), entity.getLugar_actividadId());
		Assert.assertEquals(dto.getExpositor_actividadId(), entity.getExpositor_actividadId());
	}
	
	@Test
	public void getActividadsTest(){
		List<ActividadDTO> list=actividadPersistence.getActividads();
		Assert.assertEquals(list.size(), data.size());
        for(ActividadDTO dto:list){
        	boolean found=false;
            for(ActividadEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getActividadTest(){
		ActividadEntity entity=data.get(0);
		ActividadDTO dto=actividadPersistence.getActividad(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getCosto(), dto.getCosto());
		Assert.assertEquals(entity.getHora(), dto.getHora());
		Assert.assertEquals(entity.getLugar_actividadId(), dto.getLugar_actividadId());
		Assert.assertEquals(entity.getExpositor_actividadId(), dto.getExpositor_actividadId());
        
	}
	
	@Test
	public void deleteActividadTest(){
		ActividadEntity entity=data.get(0);
		actividadPersistence.deleteActividad(entity.getId());
        ActividadEntity deleted=em.find(ActividadEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateActividadTest(){
		ActividadEntity entity=data.get(0);
		
		ActividadDTO dto=new ActividadDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setCosto(generateRandom(Long.class));
dto.setFecha(generateRandomDate());
		dto.setHora(generateRandom(String.class));
		dto.setLugar_actividadId(generateRandom(Long.class));
		dto.setExpositor_actividadId(generateRandom(Long.class));
		
		
		actividadPersistence.updateActividad(dto);
		
		
		ActividadEntity resp=em.find(ActividadEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getCosto(), resp.getCosto());	
Assert.assertEquals(parseDate(dto.getFecha()), resp.getFecha());
		Assert.assertEquals(dto.getHora(), resp.getHora());	
		Assert.assertEquals(dto.getLugar_actividadId(), resp.getLugar_actividadId());	
		Assert.assertEquals(dto.getExpositor_actividadId(), resp.getExpositor_actividadId());	
	}
	
	@Test
	public void getActividadPaginationTest(){
		//Page 1
		ActividadPageDTO dto1=actividadPersistence.getActividads(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ActividadPageDTO dto2=actividadPersistence.getActividads(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ActividadDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ActividadEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ActividadDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ActividadEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}