/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence.api;

import co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence.entity.Estadisticasdia_InscripcionEntity;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.master.persistence.entity.EstadisticasempresaEntity;
import co.edu.uniandes.csw.G3xtreme.empresa.logic.dto.EmpresaDTO;
import co.edu.uniandes.csw.G3xtreme.estadisticas.master.logic.dto.EstadisticasMasterDTO;
import java.util.List;

public interface _IEstadisticasMasterPersistence {

	public EstadisticasMasterDTO getEstadisticas(Long estadisticasId);
	
	
    public Estadisticasdia_InscripcionEntity createEstadisticasdia_InscripcionEntity(Estadisticasdia_InscripcionEntity entity);
    public void deleteEstadisticasdia_InscripcionEntity(Long estadisticasId, Long dia_InscripcionId);
    public List<Dia_InscripcionDTO> getEstadisticasdia_InscripcionEntityList(Long estadisticasId);
    public EstadisticasempresaEntity createEstadisticasempresaEntity(EstadisticasempresaEntity entity);
    public void deleteEstadisticasempresaEntity(Long estadisticasId, Long empresaId);
    public List<EmpresaDTO> getEstadisticasempresaEntityList(Long estadisticasId);
   
  
}
