/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionDTO;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.dto.Dia_InscripcionPageDTO;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.logic.api._IDia_InscripcionLogicService;
import co.edu.uniandes.csw.G3xtreme.dia_inscripcion.persistence.api.IDia_InscripcionPersistence;

public abstract class _Dia_InscripcionLogicService implements _IDia_InscripcionLogicService {

	@Inject
	protected IDia_InscripcionPersistence persistance;

	public Dia_InscripcionDTO createDia_Inscripcion(Dia_InscripcionDTO dia_Inscripcion){
		return persistance.createDia_Inscripcion( dia_Inscripcion); 
    }

	public List<Dia_InscripcionDTO> getDia_Inscripcions(){
		return persistance.getDia_Inscripcions(); 
	}

	public Dia_InscripcionPageDTO getDia_Inscripcions(Integer page, Integer maxRecords){
		return persistance.getDia_Inscripcions(page, maxRecords); 
	}

	public Dia_InscripcionDTO getDia_Inscripcion(Long id){
		return persistance.getDia_Inscripcion(id); 
	}

	public void deleteDia_Inscripcion(Long id){
	    persistance.deleteDia_Inscripcion(id); 
	}

	public void updateDia_Inscripcion(Dia_InscripcionDTO dia_Inscripcion){
	    persistance.updateDia_Inscripcion(dia_Inscripcion); 
	}	
}