/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.lugar.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G3xtreme.lugar.logic.dto.LugarPageDTO;
import co.edu.uniandes.csw.G3xtreme.lugar.logic.dto.LugarDTO;
import co.edu.uniandes.csw.G3xtreme.lugar.persistence.api.ILugarPersistence;
import co.edu.uniandes.csw.G3xtreme.lugar.persistence.entity.LugarEntity;
import co.edu.uniandes.csw.G3xtreme.lugar.persistence.converter.LugarConverter;
import static co.edu.uniandes.csw.G3xtreme.util._TestUtil.*;

@RunWith(Arquillian.class)
public class LugarPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(LugarPersistence.class.getPackage())
				.addPackage(LugarEntity.class.getPackage())
				.addPackage(ILugarPersistence.class.getPackage())
                .addPackage(LugarDTO.class.getPackage())
                .addPackage(LugarConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ILugarPersistence lugarPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from LugarEntity").executeUpdate();
	}

	private List<LugarEntity> data=new ArrayList<LugarEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			LugarEntity entity=new LugarEntity();
			entity.setName(generateRandom(String.class));
			entity.setDireccion(generateRandom(String.class));
			entity.setCosto(generateRandom(Long.class));
			entity.setDetalles(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createLugarTest(){
		LugarDTO dto=new LugarDTO();
		dto.setName(generateRandom(String.class));
		dto.setDireccion(generateRandom(String.class));
		dto.setCosto(generateRandom(Long.class));
		dto.setDetalles(generateRandom(String.class));
		
		LugarDTO result=lugarPersistence.createLugar(dto);
		
		Assert.assertNotNull(result);
		
		LugarEntity entity=em.find(LugarEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDireccion(), entity.getDireccion());
		Assert.assertEquals(dto.getCosto(), entity.getCosto());
		Assert.assertEquals(dto.getDetalles(), entity.getDetalles());
	}
	
	@Test
	public void getLugarsTest(){
		List<LugarDTO> list=lugarPersistence.getLugars();
		Assert.assertEquals(list.size(), data.size());
        for(LugarDTO dto:list){
        	boolean found=false;
            for(LugarEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getLugarTest(){
		LugarEntity entity=data.get(0);
		LugarDTO dto=lugarPersistence.getLugar(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDireccion(), dto.getDireccion());
		Assert.assertEquals(entity.getCosto(), dto.getCosto());
		Assert.assertEquals(entity.getDetalles(), dto.getDetalles());
        
	}
	
	@Test
	public void deleteLugarTest(){
		LugarEntity entity=data.get(0);
		lugarPersistence.deleteLugar(entity.getId());
        LugarEntity deleted=em.find(LugarEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateLugarTest(){
		LugarEntity entity=data.get(0);
		
		LugarDTO dto=new LugarDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setDireccion(generateRandom(String.class));
		dto.setCosto(generateRandom(Long.class));
		dto.setDetalles(generateRandom(String.class));
		
		
		lugarPersistence.updateLugar(dto);
		
		
		LugarEntity resp=em.find(LugarEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDireccion(), resp.getDireccion());	
		Assert.assertEquals(dto.getCosto(), resp.getCosto());	
		Assert.assertEquals(dto.getDetalles(), resp.getDetalles());	
	}
	
	@Test
	public void getLugarPaginationTest(){
		//Page 1
		LugarPageDTO dto1=lugarPersistence.getLugars(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        LugarPageDTO dto2=lugarPersistence.getLugars(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(LugarDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(LugarEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(LugarDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(LugarEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}