/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.rol.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.G3xtreme.rol.logic.dto.RolDTO;
import co.edu.uniandes.csw.G3xtreme.rol.logic.dto.RolPageDTO;
import co.edu.uniandes.csw.G3xtreme.rol.logic.api._IRolLogicService;
import co.edu.uniandes.csw.G3xtreme.rol.persistence.api.IRolPersistence;

public abstract class _RolLogicService implements _IRolLogicService {

	@Inject
	protected IRolPersistence persistance;

	public RolDTO createRol(RolDTO rol){
		return persistance.createRol( rol); 
    }

	public List<RolDTO> getRols(){
		return persistance.getRols(); 
	}

	public RolPageDTO getRols(Integer page, Integer maxRecords){
		return persistance.getRols(page, maxRecords); 
	}

	public RolDTO getRol(Long id){
		return persistance.getRol(id); 
	}

	public void deleteRol(Long id){
	    persistance.deleteRol(id); 
	}

	public void updateRol(RolDTO rol){
	    persistance.updateRol(rol); 
	}	
}