/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.G3xtreme.foro.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G3xtreme.foro.logic.dto.ForoDTO;
import co.edu.uniandes.csw.G3xtreme.foro.logic.api.IForoLogicService;
import co.edu.uniandes.csw.G3xtreme.foro.master.logic.api._IForoMasterLogicService;
import co.edu.uniandes.csw.G3xtreme.foro.master.logic.dto.ForoMasterDTO;
import co.edu.uniandes.csw.G3xtreme.dia.logic.api.IDiaLogicService;
import co.edu.uniandes.csw.G3xtreme.coordinador.logic.api.ICoordinadorLogicService;
import co.edu.uniandes.csw.G3xtreme.fase.logic.api.IFaseLogicService;
import co.edu.uniandes.csw.G3xtreme.dia.logic.dto.DiaDTO;
import co.edu.uniandes.csw.G3xtreme.coordinador.logic.dto.CoordinadorDTO;
import co.edu.uniandes.csw.G3xtreme.fase.logic.dto.FaseDTO;
import javax.inject.Inject;


public abstract class _ForoMasterMockLogicService implements _IForoMasterLogicService {

    protected static ArrayList<ForoMasterDTO> foroMasterDtosList = new ArrayList<ForoMasterDTO>() ;
    @Inject
    protected IDiaLogicService diaPersistance;
    @Inject
    protected ICoordinadorLogicService coordinadorPersistance;
    @Inject
    protected IFaseLogicService fasePersistance;
    @Inject
    protected IForoLogicService foroPersistance;

    public ForoMasterDTO createMasterForo(ForoMasterDTO foro) {

        foroPersistance.createForo(foro.getForoEntity());
        for (FaseDTO dto : foro.getCreatefase_foro()) {
            fasePersistance.createFase(dto);
        }
        for (CoordinadorDTO dto : foro.getCreatecoordinador_foro()) {
            coordinadorPersistance.createCoordinador(dto);
        }
        for (DiaDTO dto : foro.getCreatedia_foro()) {
            diaPersistance.createDia(dto);
        }
        foroMasterDtosList.add(foro);
        return foro;
    }

    public ForoMasterDTO getMasterForo(Long id) {
        for (ForoMasterDTO foroMasterDTO : foroMasterDtosList) {
            if (foroMasterDTO.getForoEntity().getId() == id) {
                return foroMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterForo(Long id) {
        for (ForoMasterDTO foroMasterDTO : foroMasterDtosList) {
            if (foroMasterDTO.getForoEntity().getId() == id) {

                for (FaseDTO dto : foroMasterDTO.getCreatefase_foro()) {
                    fasePersistance.deleteFase(dto.getId());
                }
                foroPersistance.deleteForo(foroMasterDTO.getId());
                foroMasterDtosList.remove(foroMasterDTO);
                for (CoordinadorDTO dto : foroMasterDTO.getCreatecoordinador_foro()) {
                    coordinadorPersistance.deleteCoordinador(dto.getId());
                }
                foroPersistance.deleteForo(foroMasterDTO.getId());
                foroMasterDtosList.remove(foroMasterDTO);
                for (DiaDTO dto : foroMasterDTO.getCreatedia_foro()) {
                    diaPersistance.deleteDia(dto.getId());
                }
                foroPersistance.deleteForo(foroMasterDTO.getId());
                foroMasterDtosList.remove(foroMasterDTO);
            }
        }

    }

    public void updateMasterForo(ForoMasterDTO foro) {

        // update Fase
        if (foro.getUpdatefase_foro() != null) {
            for (FaseDTO dto : foro.getUpdatefase_foro()) {
                fasePersistance.updateFase(dto);
            }
        }
        // persist new Fase
        if (foro.getCreatefase_foro() != null) {
            for (FaseDTO dto : foro.getCreatefase_foro()) {
                FaseDTO persistedFaseDTO = fasePersistance.createFase(dto);
                dto = persistedFaseDTO;
            }
        }
        // delete Fase
        if (foro.getDeletefase_foro() != null) {
            for (FaseDTO dto : foro.getDeletefase_foro()) {

                fasePersistance.deleteFase(dto.getId());
            }
        }
        // update Coordinador
        if (foro.getUpdatecoordinador_foro() != null) {
            for (CoordinadorDTO dto : foro.getUpdatecoordinador_foro()) {
                coordinadorPersistance.updateCoordinador(dto);
            }
        }
        // persist new Coordinador
        if (foro.getCreatecoordinador_foro() != null) {
            for (CoordinadorDTO dto : foro.getCreatecoordinador_foro()) {
                CoordinadorDTO persistedCoordinadorDTO = coordinadorPersistance.createCoordinador(dto);
                dto = persistedCoordinadorDTO;
            }
        }
        // delete Coordinador
        if (foro.getDeletecoordinador_foro() != null) {
            for (CoordinadorDTO dto : foro.getDeletecoordinador_foro()) {

                coordinadorPersistance.deleteCoordinador(dto.getId());
            }
        }
        // update Dia
        if (foro.getUpdatedia_foro() != null) {
            for (DiaDTO dto : foro.getUpdatedia_foro()) {
                diaPersistance.updateDia(dto);
            }
        }
        // persist new Dia
        if (foro.getCreatedia_foro() != null) {
            for (DiaDTO dto : foro.getCreatedia_foro()) {
                DiaDTO persistedDiaDTO = diaPersistance.createDia(dto);
                dto = persistedDiaDTO;
            }
        }
        // delete Dia
        if (foro.getDeletedia_foro() != null) {
            for (DiaDTO dto : foro.getDeletedia_foro()) {

                diaPersistance.deleteDia(dto.getId());
            }
        }
    }
}