/* ========================================================================
 * Copyright 2014 G3xtreme
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G3xtreme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G3xtreme.foro.master.persistence.entity;

import co.edu.uniandes.csw.G3xtreme.actividad.persistence.entity.ActividadEntity;
import co.edu.uniandes.csw.G3xtreme.foro.persistence.entity.ForoEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(ForoactividadEntityId.class)
@NamedQueries({
    @NamedQuery(name = "ForoactividadEntity.getByMasterId", query = "SELECT  u FROM ForoactividadEntity u WHERE u.foroId=:foroId"),
    @NamedQuery(name = "ForoactividadEntity.deleteForoactividadEntity", query = "DELETE FROM ForoactividadEntity u WHERE u.foroId=:foroId and  u.actividadId=:actividadId")
})
public class ForoactividadEntity implements Serializable {

    @Id
    @Column(name = "foroId")
    private Long foroId;
    @Id
    @Column(name = "actividadId")
    private Long actividadId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "foroId", referencedColumnName = "id")
    @JoinFetch
    private ActividadEntity foroIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "actividadId", referencedColumnName = "id")
    @JoinFetch
    private ActividadEntity actividadIdEntity; 

    public ForoactividadEntity() {
    }

    public ForoactividadEntity(Long foroId, Long actividadId) {
        this.foroId =foroId;
        this.actividadId = actividadId;
    }

    public Long getForoId() {
        return foroId;
    }

    public void setForoId(Long foroId) {
        this.foroId = foroId;
    }

    public Long getActividadId() {
        return actividadId;
    }

    public void setActividadId(Long actividadId) {
        this.actividadId = actividadId;
    }

    public ActividadEntity getForoIdEntity() {
        return foroIdEntity;
    }

    public void setForoIdEntity(ActividadEntity foroIdEntity) {
        this.foroIdEntity = foroIdEntity;
    }

    public ActividadEntity getActividadIdEntity() {
        return actividadIdEntity;
    }

    public void setActividadIdEntity(ActividadEntity actividadIdEntity) {
        this.actividadIdEntity = actividadIdEntity;
    }

}
